DSD-91: Image component lazy loading
NYPL/nypl-design-system pull request #1039
Opened 2022-06-07 16:35 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-91](https://jira.nypl.org/browse/DSD-91)

## This PR does the following:

- Adds lazy loading for images in the `Image` component with the help of the `react-intersection-observer` and `@charlietango/use-native-lazy-loading` npm packages.
- First, if the browser supports the native `loading="true"` `img` attribute, then use it. Otherwise, the IntersectionObserver API is used.

## How has this been tested?

- In Storybook through the "Network" tab in Chrome's console window for the `Card`, `SimpleGrid`, `Hero`, `Image`, `StructuredContent`, and `Table` components.
- Note that tests that use the `Image` component internally need the `IntersectionObserver` API to be mocked with the `mockAllIsIntersecting(true);` call.

## Accessibility concerns or updates

- N/A.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2022-06-07 16:36 UTC, EdwinGuzman commented on src/components/Card/Card.test.tsx
> +  it("Generates a card with the full-click functionality", () => {
Updated this title because it was a copy/paste.

2022-06-07 16:36 UTC, EdwinGuzman commented on src/components/Hero/Hero.test.tsx
> +describe("Hero accessbility tests", () => {
Moved accessibility tests to a separate "describe".

2022-06-13 17:33 UTC, bigfishdesign13 requested changes
This is working well, but I would like to make one additional change.  Add a background color to the `img` element to act as a placeholder as image files load.

```
backgroundColor: "ui.gray.x-light-cool”,
```

2022-06-13 17:33 UTC, bigfishdesign13 commented on src/components/Image/Image.stories.mdx
> +them. Once the image's wrapper is in view, we load the image by rendering it
Provided by who?  What does `them` refer to?  The two packages?

2022-06-14 18:29 UTC, EdwinGuzman commented
Updated. It's hard to see the background gray color placeholder but I slowed down the network and took some screenshots:
<img width="755" alt="Screen Shot 2022-06-14 at 2 23 20 PM" src="https://user-images.githubusercontent.com/1280564/173662705-cdd85fb4-37b1-47fd-aaf6-f3946a4310dd.png">
<img width="868" alt="Screen Shot 2022-06-14 at 2 23 33 PM" src="https://user-images.githubusercontent.com/1280564/173662731-815fefc5-4d68-4149-a2c6-156961c9d570.png">

So, unless if you do this or have slow internet connection, it'll be very subtle.

2022-06-14 21:14 UTC, bigfishdesign13 approved these changes
Very nice.

2022-06-14 21:27 UTC, merged