DSD-1021 - Heading case styles
NYPL/nypl-design-system pull request #1053
Opened 2022-06-16 01:32 UTC by knezmilos

Fixes JIRA ticket DSD-1021

## This PR does the following:

- Adds capitalized, upper case, lower case text styles for `Heading` component

## How has this been tested?

Storybook

## Accessibility concerns or updates

-

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2022-06-16 18:23 UTC, bigfishdesign13 requested changes
Overall, this looke good.  There’s just one typo and one nit that need to be fixed.

2022-06-16 18:23 UTC, bigfishdesign13 commented on src/components/Heading/Heading.tsx
> +        "NYPL Reservoir Text: Multiple text case props have been passed " +
Typo.  Change to `NYPL Reservoir Heading: ...`

2022-06-16 18:23 UTC, bigfishdesign13 commented on src/components/Heading/Heading.tsx
> +      isCapitalized,
Please alphabetize the list of props.  It looks like one or two may have been out of order to begin with.

2022-06-17 14:21 UTC, EdwinGuzman commented on src/components/Heading/Heading.tsx
> +  /** Optional prop used to show capitalized text */
This list of props should also be alphabetized.

2022-06-21 14:21 UTC, EdwinGuzman approved these changes

2022-06-21 14:53 UTC, bigfishdesign13 approved these changes
Looks good.

2022-06-21 15:04 UTC, merged