DSD-1060: Header Docs
NYPL/nypl-design-system pull request #1089
Opened 2022-07-21 16:46 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-1051](https://jira.nypl.org/browse/DSD-1060)

## This PR does the following:

- Adds documentation for the `Header` component in Storybook. Some sections are missing but will be completed by @oliviawongnyc 

## How has this been tested?

Locally

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2022-07-21 17:42 UTC, EdwinGuzman commented
Specific `Header` Storybook documentation: https://nypl-design-system-git-dsd-1060-header-docs-nypl.vercel.app/?path=/docs/components-page-layout-header--header

2022-07-22 12:33 UTC, bigfishdesign13 requested changes
This looks pretty good.  I made a few suggestions for some of the language.

2022-07-22 12:33 UTC, bigfishdesign13 commented on src/components/Header/Header.stories.mdx
> +The `Header` component is a complete and complex component that fetches data
I think this paragraph would be more effective as a bulleted list.

2022-07-22 12:33 UTC, bigfishdesign13 commented on src/components/Header/Header.stories.mdx
> +- Dropdowns focus features - Each dropdown button and menu combination uses a
The intial label for this line could be better.  `Dropdown Buttons with Focus Trapping`?

2022-07-22 12:33 UTC, bigfishdesign13 commented on src/components/Header/Header.stories.mdx
> +The `Header` component implements the DS' own `SkipNavigation` component. More
I think you can get away with not using an apostrophe in instances like this.  You can just says `...the DS SkipNavigation component...`?

2022-07-22 12:33 UTC, bigfishdesign13 commented on src/components/Header/Header.stories.mdx
> +- Skip navigation - More information about this feature in the following section.
With the `SkipNavigation` component being implemented here, we need to talk about what should be done with `Template`.

2022-07-22 12:33 UTC, bigfishdesign13 commented on src/components/Header/Header.stories.mdx
> +### Desktop
Add `TBD` below this heading.

2022-07-22 12:33 UTC, bigfishdesign13 commented on src/components/Header/Header.stories.mdx
> +When logged in, it will display the patron's name and an additional "logout" link.
What is `it`?  The `Login Drown Menu`?

We also need to watch how `Log In` is written in the docs.  The menu shows it with a space, so the docs should do the same.  Personaly, I don’t think it shoudl be written with a space, but that’s how it was done in the menu, so we’ll need to follow that pattern in the docs.

2022-07-22 12:33 UTC, bigfishdesign13 commented on src/components/Header/Header.stories.mdx
> +search in two separate resources. In the search form, the patron can choose
Update the last sentece.

_When using the search form, a patron can choose which location to search._

2022-07-22 12:33 UTC, bigfishdesign13 commented on src/components/Header/Header.stories.mdx
> +search in two separate resources. In the search form, the patron can choose
Change `resources` to `locations` and then list the locations: _the library Catalog or the NYPL.org website._

2022-07-22 12:33 UTC, bigfishdesign13 commented on src/components/Header/Header.stories.mdx
> +is the Catalog. For example, the [Catalog search](https://browse.nypl.org/iii/encore/search/C__Scats__Orightresult__U?lang=eng&suite=def)
_For example, please see the…_

2022-07-22 12:33 UTC, bigfishdesign13 commented on src/components/Header/Header.stories.mdx
> +to search the appropriate resource.
For consistency, change `resource` to `location`.

2022-07-22 12:33 UTC, bigfishdesign13 commented on src/components/Header/Header.stories.mdx
> +the form, choose the appropriate resource, and click on the search button or
Again, for consistency, change `resource` to `location`.

2022-07-22 12:33 UTC, bigfishdesign13 commented on src/components/Header/Header.stories.mdx
> +In the mobile view, the patron needs to click on the hamburger menu icon button
The links and buttons in the header get all mixed up in the mobile view, so I think we need to be careful about trying to describe what shows where.  You mention that the `Locations` button is treated differently, so should we also talk about the `Log In` and `Search` buttons?

2022-07-22 12:33 UTC, bigfishdesign13 commented on src/components/Header/Header.stories.mdx
> +There are occassions when a patron logs out from either the Catalog, the
This could use some clarity.

_There are occassions when a patron may log out directly from either the Catalog or the Research Catalog, or log out by using the log out link in the `Header` component.  Because of this, there is a mismatch..._

2022-07-22 15:20 UTC, oliviawongnyc requested changes
Very thoughtfully done documentation, Edwin!! My only general comment: I thought that some of the descriptions got very specific, like the sections about how the links are laid out in the desktop and mobile views. I would expect a developer who was getting acquainted with the `Header` to get this information by interacting with the component as rendered in Storybook. What do you think?

2022-07-22 15:20 UTC, oliviawongnyc commented on src/components/Header/components/HeaderLogin.tsx
> + * out, and also displays the patron's name if they are logged in.
Also contains links to go to the catalogs if logged in.

2022-07-22 15:20 UTC, oliviawongnyc commented on src/components/Header/components/HeaderLoginButton.tsx
> + * and keep focus trapped within the menu.
It will display, "Login" or "My Account" depending on whether the user is logged in.

2022-07-22 15:20 UTC, oliviawongnyc commented on src/components/Header/components/HeaderLowerNav.tsx
> + * navigate different landing pages on NYPL.org.
Maybe "navigate _to_ different..."?

2022-07-22 15:20 UTC, oliviawongnyc commented on src/components/Header/Header.stories.mdx
> +- Notification `<aside>` HTML element - This element is rendered above the
Can be shortened a bit:

- Notification `<aside>` HTML element - This landmark element renders NYPL alert messages. Per accessibility guidelines, it cannot be nested within the `<header>` element, so it is rendered above. More information can be found in the
  [Notification Accessibility](https://nypl.github.io/nypl-design-system/reservoir/v1/?path=/docs/components-feedback-notification--notification-with-controls#Accessibility) section.

2022-07-22 15:20 UTC, oliviawongnyc commented on src/components/Header/Header.stories.mdx
> +  this landmark element is present.
Personally think you don't need this last bit as we already know these elements are in the `Header`: "...and using the `Header` component will ensure this landmark element is present."

2022-07-22 15:20 UTC, oliviawongnyc commented on src/components/Header/Header.stories.mdx
> +  focus trap feature to appropriately tab through the contents in the menu that
"children" rather than "contents"?

2022-07-22 15:20 UTC, oliviawongnyc commented on src/components/Header/Header.stories.mdx
> +and about why we should use in its
Nit: can remove the second "about" and add an "it":

 "...and why we should use it in its..."

2022-07-22 15:20 UTC, oliviawongnyc commented on src/components/Header/Header.stories.mdx
> +When logged in, it will display the patron's name and an additional "logout" link.
Agree we should be consistent. I think technically: if the word is a noun or adjective, you should use one word (login), for verbs, use two words (log in).

2022-07-22 15:20 UTC, oliviawongnyc commented on src/components/Header/Header.stories.mdx
> +link.
Might we be able to include a picture of what the iframe looks like?

2022-07-25 14:04 UTC, EdwinGuzman commented on src/components/Header/Header.stories.mdx
> +- Skip navigation - More information about this feature in the following section.
Yes, but it is possible for someone to use the `Template` component and not use the `Header` in non-NYPL products. Or, use a different NYPL header such as what's in MLN.

2022-07-25 14:27 UTC, EdwinGuzman commented on src/components/Header/Header.stories.mdx
> +link.
The style is set to display none so it's not visible. I'll include that.

2022-07-25 20:57 UTC, bigfishdesign13 requested changes
A few more questions.

2022-07-25 20:57 UTC, bigfishdesign13 commented on src/components/Header/Header.stories.mdx
> +The `Header` component implements the DS own `SkipNavigation` component. More
Drop `own` as well.

2022-07-25 20:57 UTC, bigfishdesign13 commented on src/components/Header/Header.stories.mdx
> +### Desktop
Will you be adding anything under this heading?

2022-07-25 20:57 UTC, bigfishdesign13 commented on src/components/Header/Header.stories.mdx
> +The `Header` component implements the DS own `SkipNavigation` component. More
So, for now, when a consuming app uses all DS components, the app will need to explicitly disable `SkipNavigation` within `Template`, right?  Can you add somethign here about that?

2022-07-26 14:24 UTC, EdwinGuzman commented on src/components/Header/Header.stories.mdx
> +### Desktop
Olivia worked on that in a separate PR.

2022-07-26 17:01 UTC, bigfishdesign13 approved these changes
The changes look good!

2022-07-27 18:59 UTC, oliviawongnyc approved these changes

2022-07-27 20:03 UTC, merged