DSD-1075: MultiSelect accessibility fixes
NYPL/nypl-design-system pull request #1112
Opened 2022-08-08 18:26 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-1075](https://jira.nypl.org/browse/DSD-1075)

## This PR does the following:

### Issue 1

This fixes the accessibility issue `"Interactive controls must not be nested"` found by axe when items are selected: the selected count button that renders inside the `MultiSelectMenuButton` is the issue. When using VoiceOver on a Mac, I was able to focus on both the menu button and the selected count button and VoiceOver read _both_ buttons correctly. So, on an n=1 test case, it worked for me. I did not test on other machines with other screenreaders so I do think it's still an issue.

The proposed update is going from

```jsx
<button ...>
  <span role="button">
    <span>2</span><svg>
  </span>
  <span>title</title>
  <svg>
</button>
```

to 

```jsx
<>
  <button ...>
    <span>title</title>
    <svg>
  </button>
  <span role="button">
    <span>2</span><svg>
  </span>
</>
```

The selected count button now renders _after_ the main button but is still visually displayed above the main menu button. This also helps prevent click events from the selected count button from bubbling up to the main button (as noted in two unit tests).

An `aria-label` was also added so that screen readers now read the button with context. Before, it use to say something like "2 MultiSelect Listbox" when it read the entire button which can be confusing. It also just read "2" for the selected count button itself.

<img width="424" alt="Screen Shot 2022-08-08 at 2 15 13 PM" src="https://user-images.githubusercontent.com/1280564/183485752-1199ca8f-e3a3-4b4e-a791-99e38c4d3c2a.png">

With the update:

<img width="708" alt="Screen Shot 2022-08-08 at 12 43 53 PM" src="https://user-images.githubusercontent.com/1280564/183485787-49a288ad-6702-4f5a-ab56-0ab84c7b385c.png">

### Issue 2

The second issue is `"Elements should not have tabindex greater than zero". This occurs for the "dialog" variant when it is opened and is caused by the `react-focus-lock` usage (which is used by Chakra's `focus-lock` implementation). I think in this case we can proceed and say that we _know_ this is an issue and a limitation, but also part of expected behavior we want to implement. While is not directly an issue we implemented, it's caused by something we use that implements a behavior we want. Typically, someone would write a VPAT document to list this issue but I'm not sure who would do it in this case or that is the right approach.

For now, let's list this down in the Storybook doc as something we know is an issue but doesn't affect component or app usage when it is rendered. It is only and issue when it is opened but something we can live with since we _want_ to trap focus within the component and the rest of the page is irrelevant.

## How has this been tested?

Locally in Storybook.

## Accessibility concerns or updates

- Yeah, fixes one and explicitly lists down an issue we will have to proceed with until a better solution appears in the near (?) future.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2022-08-09 20:49 UTC, bigfishdesign13 requested changes
This looks good, except for one style change.

I just took a look at the [Multiselect](https://carbondesignsystem.com/components/dropdown/usage/#multiselect) variant of Carbon’s `Dropdown` component and they have it setup with the same structure that is throwing the error for our component.

2022-08-09 20:49 UTC, bigfishdesign13 commented on src/theme/components/multiSelectMenuButton.ts
> +      marginLeft: hasSelectedItems ? "50px" : "0",
Now that the selected items button is not displacing the button label text, we are losing the animation on the label text.  I thought the `transition` attribute was built into the CSS for all elements, but it looks like that is not the case and we’ll need to add the following for `buttonLabel`.

`transition: "margin 150ms ease-out”`

But that should only be applied when the first checkbox is selected.  When clearing the checkboxes, the selected items button disappears immediately, so the marign on the label text should not transition from 50 back to 0.  It should jump immediately from one to the next.  I am not sure which variable would indicate that action.

2022-08-09 21:26 UTC, EdwinGuzman commented
> I just took a look at the [Multiselect](https://carbondesignsystem.com/components/dropdown/usage/#multiselect) variant of Carbon’s Dropdown component and they have it setup with the same structure that is throwing the error for our component.

Yes, and the error exists (axe in devtools):

<img width="1377" alt="Screen Shot 2022-08-09 at 5 11 06 PM" src="https://user-images.githubusercontent.com/1280564/183764408-0bc4fa0c-90d2-452a-9b96-c63347620f5e.png">

2022-08-10 13:57 UTC, EdwinGuzman commented
@bigfishdesign13 added the animation. Not much needs to be done because the `margin-left` style is added when there is at least one item selected, so it doesn't have to further check or name sure it's not added again. Likewise, when it's removed, the animation still kicks in.

2022-08-10 14:44 UTC, bigfishdesign13 approved these changes
Smooth.

2022-08-10 14:44 UTC, bigfishdesign13 commented on src/theme/components/multiSelectMenuButton.ts
> +      transition: "margin 150ms ease-out",
Nit: alphabetize the props

2022-09-08 14:59 UTC, merged