Dsd 1106/dark mode feedback cat
NYPL/nypl-design-system pull request #1137
Opened 2022-09-15 20:37 UTC by oliviawongnyc

Fixes JIRA ticket [DSD-1106](https://jira.nypl.org/browse/DSD-1106).

## This PR does the following:

- Adds `dark mode` color mode support for the `Notification`, `ProgressIndicator`, and `SkeletonLoader` components.
- Deprecates the `darkMode` prop in the `ProgressIndicator` component.

## How has this been tested?

- Locally, in Storybook.

## Accessibility concerns or updates

- None that I know of.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2022-09-15 20:40 UTC, oliviawongnyc commented
@bigfishdesign13, I merged in development, so you'll see some changes that aren't mine... is that okay?

2022-09-16 14:51 UTC, bigfishdesign13 commented
> @bigfishdesign13, I merged in development, so you'll see some changes that aren't mine... is that okay?

@oliviawongnyc What kind of changes?  Are they worthy of making a note in the PR description?

2022-09-19 16:30 UTC, oliviawongnyc commented
> > @bigfishdesign13, I merged in development, so you'll see some changes that aren't mine... is that okay?
> 
> @oliviawongnyc What kind of changes? Are they worthy of making a note in the PR description?

I added a note to the PR description about the changes that aren't mine!

2022-09-19 17:45 UTC, EdwinGuzman commented
@bigfishdesign13  not necessarily related to the updates in the PR, but why are the dark mode designs so different from the light mode designs for the `Notification` component? As far as I can tell, this is the only component where the DM version adds more to the rendered component.

2022-09-19 18:04 UTC, bigfishdesign13 commented
> @bigfishdesign13 not necessarily related to the updates in the PR, but why are the dark mode designs so different from the light mode designs for the `Notification` component? As far as I can tell, this is the only component where the DM version adds more to the rendered component.

@EdwinGuzman 
Visually, the only real structural difference betwen the light and dark mode variants is the addition of the color bar for dark mode.  We needed a subtle way to use the bright colors and this is where we settled.  I thought about only applying the color to the icon, but it just wasn’t enough and the impact of the color (and the what it implied) was lost.  The addition of the color bar increased the impact of the color, but keeping restricted to a small area kept it from becoming overwhelming.

2022-09-19 18:28 UTC, EdwinGuzman commented on src/theme/components/progressIndicator.ts
> +          _dark: "dark.ui.focus",
I think you need the key attribute `{ outline: "dark.ui.focus" }` instead of just adding the value to `_dark`.

2022-09-19 18:34 UTC, EdwinGuzman reviewed
Looks good just the one comment about adding the value directly to the `_dark` key in `ProgressIndicator`.

2022-09-19 19:58 UTC, EdwinGuzman commented
I missed the `StatusBadge` because that was already merged in. I kinda like the dark mode variants for these two more than the light ones 😅 . I get the need to make the color more apparent and have more impact, it just feels like a new component design from the "original" light variant. It's not a problem but just the difference can be confusing if a user expects a similar dark mode variant.

2022-09-19 20:00 UTC, EdwinGuzman approved these changes
Looks good to me.

2022-09-21 16:00 UTC, bigfishdesign13 requested changes
One small style fix is needed.  There are also some spacing issues related to the mobile view for `Notification`, but I will create another ticket to address those issues if/when we convert the light mode variant to have the same structure as the dark mode variant.

2022-09-21 16:00 UTC, bigfishdesign13 commented on src/theme/components/progressIndicator.ts
> +                stroke: "dark.ui.bg.active",
For better `a11y` compliance, change this to `dark.ui.bg.hover`.

2022-09-21 16:00 UTC, bigfishdesign13 commented on src/theme/components/progressIndicator.ts
> +              _dark: { stroke: "dark.ui.focus" },
My apologies.  I had this color value set incorrectly in the Figma.  Change this to `dark.ui.link.primary`.

2022-09-21 16:00 UTC, bigfishdesign13 commented on src/theme/components/progressIndicator.ts
> +          _dark: "dark.ui.focus",
Is this shorthard?  There is no CSS attribute.  Either way, due to my mistake in the Figma, please change this color value to `dark.ui.link.primary`.

2022-09-21 16:00 UTC, bigfishdesign13 commented on src/theme/components/progressIndicator.ts
> +          bg: "dark.ui.bg.active",
For better `a11y` compliance, change this to `dark.ui.bg.hover`.

2022-09-21 16:00 UTC, bigfishdesign13 commented on src/components/Notification/Notification.stories.mdx
> +      dismissible: true,
Why was this flipped from `false` to `true`?

2022-09-21 16:00 UTC, bigfishdesign13 commented on src/theme/components/notification.ts
> +        ml: icon ? "xs" : "0",
Because of the new positioning of the icon, this should also be “0” when `isCentered` is true.

2022-09-23 13:50 UTC, bigfishdesign13 approved these changes
Looks good!

2022-09-23 14:21 UTC, merged