MultiSelect/ FilterBar Feature Branch
NYPL/nypl-design-system pull request #1166
Opened 2022-10-11 16:28 UTC by isastettler

Fixes JIRA ticket xxx

## This PR does the following:

-

## How has this been tested?

## Accessibility concerns or updates

-

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2022-10-12 21:52 UTC, EdwinGuzman commented
Let's review this one more time. Isa pointed out that the updated `Button` styles (for the sizes) altered the `MultiSelect`.

2022-10-13 19:24 UTC, bigfishdesign13 requested changes
Some CSS adjustments are needed.  Please see my comments.

2022-10-13 19:24 UTC, bigfishdesign13 commented on src/theme/components/multiSelectMenuButton.ts
> +const MultiSelectMenuButton = {
Add the following to the top of the doc…
```
import { defaultElementSizes } from "./global”;
```

2022-10-13 19:24 UTC, bigfishdesign13 commented on src/theme/components/multiSelectMenuButton.ts
> +      padding: "8px 8px 7px 16px",
Change `7px` to `8px`.
```
padding: "8px 8px 8px 16px”,
```

2022-10-13 19:24 UTC, bigfishdesign13 commented on src/theme/components/multiSelectMenuButton.ts
> +    menuButton: {
Add the following attributes to this style block...
```
borderRadius: "button.default",
fontSize: "button.default",
minHeight: { base: defaultElementSizes.mobileFieldHeight, md: "auto" },
```

2022-10-13 19:24 UTC, bigfishdesign13 commented on src/theme/components/multiSelectMenuButton.ts
> +      top: "10px",
Update to the following…
```
top: { base: "12px", md: "10px" },
```

2022-10-21 12:47 UTC, bigfishdesign13 approved these changes
Updates look good.

2022-12-19 17:59 UTC, bigfishdesign13 approved these changes
The feature branch looks good to me.

2022-12-19 21:31 UTC, EdwinGuzman commented on src/hooks/__tests__/useFilterBar.test.ts
> +describe("usFilterBar hook", () => {
Minor typo.

2022-12-19 21:32 UTC, EdwinGuzman approved these changes
Looks good. Approving but it needs a minor update to the CHANGELOG to include the three new additions.

2022-12-20 12:26 UTC, isastettler commented on src/hooks/__tests__/useFilterBar.test.ts
> +describe("usFilterBar hook", () => {
fixed

2022-12-20 15:22 UTC, merged