DSD-1175: Replace padding for menuButton
NYPL/nypl-design-system pull request #1193
Opened 2022-11-10 16:01 UTC by isastettler

Fixes JIRA ticket xxx

## This PR does the following:

- Replaces the padding in multiSelectMenuButton with py, ps, pe to ensure RTL-friendly styling

## How has this been tested?

- run existing tests
- run storybook locally

## Accessibility concerns or updates

-

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [x] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2022-11-15 15:24 UTC, bigfishdesign13 requested changes
The styles need to be adjusted.

2022-11-15 15:24 UTC, bigfishdesign13 commented on src/theme/components/multiSelectMenuButton.ts
> +      py: "8px",
The styles on lines 31-33 are not quite right.  Please see the correct styles below.
```
px: "s",
py: "xs",
```

2022-11-16 11:40 UTC, isastettler commented on src/theme/components/multiSelectMenuButton.ts
> +      py: "8px",
Updated

2022-11-16 16:25 UTC, bigfishdesign13 approved these changes
Very nice.

2022-11-16 16:56 UTC, merged