DSD-1205: expanding color theme object
NYPL/nypl-design-system pull request #1200
Opened 2022-11-22 18:28 UTC by bigfishdesign13

Fixes JIRA ticket [DSD-1205](https://jira.nypl.org/browse/DSD-1205)

## This PR does the following:

- Adds the following color options to the color theme object: `ui.bg.page`, `ui.typography.body.inverse`, `ui.typography.heading.inverse`, `dark.ui.typography.body.inverse`, and `dark.ui.typography.heading.inverse`.

## How has this been tested?

- local Storybook

## Accessibility concerns or updates

- n/a

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2022-11-22 20:04 UTC, EdwinGuzman requested changes
The "Colors" storybook page should be updated to reflect the change. Right now, the color card for the updated values don't render correctly.

2022-11-28 23:10 UTC, EdwinGuzman approved these changes
Update is fine. Just note that the PR description has `heading.inverse` instead of `inverse.heading` (similar for the other values).

2022-11-30 19:16 UTC, bigfishdesign13 commented
@EdwinGuzman I initially added more contrast details for the typography colors, but then I got caught up in adding more info for other colors as well.  That being the case, this now needs one more review and approval.

2022-12-02 17:20 UTC, EdwinGuzman requested changes

2022-12-02 17:20 UTC, EdwinGuzman commented on src/components/StyleGuide/ColorCard.tsx
> +// import SimpleGrid from "../Grid/SimpleGrid";
Remove this.

2022-12-02 17:20 UTC, EdwinGuzman commented on src/components/StyleGuide/ColorCard.tsx
> +  darkBorder?: boolean;
These two should have comments.

2022-12-02 17:20 UTC, EdwinGuzman commented on src/components/StyleGuide/ColorCard.tsx
> +  // const grayMedium = ui.gray.medium;
Remove lines 101 to 107.

2022-12-02 17:20 UTC, EdwinGuzman commented on src/components/StyleGuide/ColorCard.tsx
> +      {/* <SimpleGrid columns={2}> */}
Remove.

2022-12-02 17:20 UTC, EdwinGuzman commented on src/components/StyleGuide/ColorCard.tsx
> +      {/* </SimpleGrid> */}
Remove.

2022-12-02 18:45 UTC, EdwinGuzman approved these changes

2022-12-02 18:55 UTC, merged