Dsd 1181/update icon colors
NYPL/nypl-design-system pull request #1201
Opened 2022-11-28 20:26 UTC by oliviawongnyc

Fixes JIRA ticket [DSD-1181.](https://jira.nypl.org/browse/DSD-1181)

## This PR does the following:

- Adds requested color options to the Icon component.
- Adds IconColors and IconNames files to cut down on repetitive lists.

## How has this been tested?

- In Storybook.

## Accessibility concerns or updates

- Are there dark versions of the section colors?

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2022-11-28 23:03 UTC, EdwinGuzman commented on CHANGELOG.md
> +- Adds additional color options to `Icon` component.
Add that the type/array structure was updated as well to make it easier to update.

2022-11-28 23:04 UTC, EdwinGuzman commented on src/components/Icons/Icon.stories.mdx
> +      options: getIconColors(),
Do the same for the `name` prop so we can update it with the Controls.

2022-11-28 23:06 UTC, EdwinGuzman commented on src/components/Icons/IconNames.tsx
> +];
Why does this not need the `as const`?

2022-11-28 23:06 UTC, EdwinGuzman requested changes
Looks good! Just one minor request and a few questions.

2022-11-29 15:05 UTC, oliviawongnyc commented on src/components/Icons/IconNames.tsx
> +];
Um not sure. I left it out accidentally. Just added.

2022-11-29 15:58 UTC, EdwinGuzman approved these changes

2022-11-30 19:13 UTC, bigfishdesign13 approved these changes
This looks good, but why is the description for the `color` prop empty on the Storybook Docs view?

2022-12-01 14:51 UTC, oliviawongnyc commented
> This looks good, but why is the description for the `color` prop empty on the Storybook Docs view?

Very strange. This is true on prod as well. I looked at the code and cannot understand why this is the only description not pulling through.

2022-12-01 14:51 UTC, merged