Updates Link styles
NYPL/nypl-design-system pull request #1218
Opened 2022-12-19 20:54 UTC by oliviawongnyc

Fixes JIRA ticket [DSD-1211](https://jira.nypl.org/browse/DSD-1211).

## This PR does the following:

- Removes underline from link by default
- Adds underline to link on hover
- Adds visited color to link + svg when necessary

## This PR does not:

- Add dark mode styling for visited links (will be a separate ticket)

## How has this been tested?

- On Storybook

## Accessibility concerns or updates

- No, this is an accessibility improvement

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2022-12-19 21:37 UTC, EdwinGuzman commented on src/theme/foundations/colors.ts
> +      tertiary: "#551A8B",
Create a variable for this after `linkPrimary` and `linkSecondary` on line 37.

2022-12-19 21:40 UTC, EdwinGuzman requested changes
The update itself looks good (though I'm pro "underlined links all the time"). Update the version in the `Link`'s storybook doc and also update its Accessibility section. @bigfishdesign13 maybe we can get some text from Clare for the removal of the underline for links. For visited links, what's in the ticket is a good start, "For accessibility and UX purposes, a visited state should be added to links."

2022-12-19 22:10 UTC, oliviawongnyc commented
> The update itself looks good (though I'm pro "underlined links all the time"). Update the version in the `Link`'s storybook doc and also update its Accessibility section. @bigfishdesign13 maybe we can get some text from Clare for the removal of the underline for links. For visited links, what's in the ticket is a good start, "For accessibility and UX purposes, a visited state should be added to links."

Added a little link about visited states. I don't know that all of the button variants have visited states.

2022-12-20 17:39 UTC, EdwinGuzman reviewed
I'm good with these changes considering more a11y documentation will be added later (as a separate ticket?).

2022-12-20 19:23 UTC, oliviawongnyc commented
> I'm good with these changes considering more a11y documentation will be added later (as a separate ticket?).

Or should we wait for Clare's input @bigfishdesign13?

2022-12-20 19:46 UTC, bigfishdesign13 commented
> > I'm good with these changes considering more a11y documentation will be added later (as a separate ticket?).
> 
> Or should we wait for Clare's input @bigfishdesign13?

@oliviawongnyc 
We can mark this PR as `approved` and then create a seprate ticket fot the docs updates.  That said, this should not be merged yet.

2022-12-20 20:08 UTC, EdwinGuzman approved these changes
Don't merge yet.

2023-01-25 17:52 UTC, oliviawongnyc commented
@bigfishdesign13, @EdwinGuzman – removed any changes related to underline from this PR

2023-02-01 21:41 UTC, EdwinGuzman approved these changes

2023-02-02 15:58 UTC, bigfishdesign13 approved these changes
Looks good.

2023-03-13 20:39 UTC, merged