DSD-1228: TextInput accessibility updates
NYPL/nypl-design-system pull request #1230
Opened 2023-01-04 16:36 UTC by oliviawongnyc

Fixes JIRA ticket [DSD-1228.](https://jira.nypl.org/browse/DSD-1228)

## This PR does the following:

- Adds `autocomplete` attribute to `TextInput`s with type `"tel"`, `"email"`, and `"url"`.
- Fixes issue where `aria-describedby` attribute was not being added to some `TextInput`s.

## How has this been tested?

- Locally in Storybook, and with a new unit test.

## Accessibility concerns or updates

- None.

### Checklist:

- [x] I have updated the Storybook documentation accordingly.
- [x] I have added relevant accessibility documentation for this pull request.
- [x] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2023-01-04 19:56 UTC, EdwinGuzman commented on src/components/TextInput/TextInput.stories.mdx
> +| Latest            | `1.3.2`    |
Make this 1.4.0 so we can bundle it in the next release.

2023-01-04 20:09 UTC, EdwinGuzman reviewed
I don't see the `autocomplete` attribute in the input element, but I should, right?

2023-01-05 14:49 UTC, bigfishdesign13 requested changes
Everything seems to be working well for me.  This PR just needs one minor addition (my comment) and one update (Edwin's comment).

@EdwinGuzman I am seeing the `autocomplete` attribute as expected.  Are you looking at a variant other than `email`, `tel` or `url`?  Only those three will show the attribute by default.

2023-01-05 14:49 UTC, bigfishdesign13 commented on src/components/TextInput/TextInput.stories.mdx
> +If the `type` prop is set to `"email"`, `"tel"`, or `"url"`, the appropriate
To support this info, add another link to the `Resources` list:

MDN HTML attribute: autocomplete
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

2023-01-05 15:08 UTC, EdwinGuzman commented
I do see the attribute now so all is good on my end.

2023-01-05 20:13 UTC, EdwinGuzman approved these changes

2023-01-05 20:59 UTC, bigfishdesign13 approved these changes
Yes.

2023-01-06 15:01 UTC, merged