DSD-1294: Update MultiSelect prop names
NYPL/nypl-design-system pull request #1241
Opened 2023-01-25 20:08 UTC by isastettler

Fixes JIRA ticket [DSD-1294](https://jira.nypl.org/browse/DSD-1294)

## This PR does the following:
- Change following prop names on MutliSelect:
&ensp; - `variant` to `type`
&ensp; - `label` to `labelText`
- Change following prop names on MutliSelectMenuButton:
&ensp; - `multiSelectLabel` to `multiSelectLabelText` 
- Update Snapshot tests

## How has this been tested?

[ ] Unit tests
[ ] Storybook

## Accessibility concerns or updates

-

### Checklist:

- [x] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [x] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2023-01-25 20:22 UTC, EdwinGuzman approved these changes
Looks okay to me. Thanks for making these changes for prop name consistency!

2023-01-25 22:07 UTC, bigfishdesign13 requested changes
The functionality looks good.  This just needs some changes to the labeling and the docs language.

2023-01-25 22:07 UTC, bigfishdesign13 commented on src/components/MultiSelect/MultiSelect.tsx
> +  /** The labelText of the MultiSelect. */
Minor adjustment:
```
The label text rendered within the MultiSelect.
```

2023-01-25 22:07 UTC, bigfishdesign13 commented on src/components/MultiSelect/MultiSelect.tsx
> +  /** The type of the MultiSelect. */
Minor adjustment:
```
The type of MultiSelect that will be rendered.
```

2023-01-25 22:07 UTC, bigfishdesign13 commented on src/components/MultiSelect/MultiSelect.stories.mdx
> +- [Component Props for MultiSelect Listbox type](#component-props-multiselect-listbox-type)
Remove `type` from this label.

2023-01-25 22:07 UTC, bigfishdesign13 commented on src/components/MultiSelect/MultiSelect.stories.mdx
> +- [Component Props for MultiSelect Dialog type](#component-props-multiselect-dialog-type)
Remove `type` from this label.

2023-01-25 22:07 UTC, bigfishdesign13 commented on src/components/MultiSelect/MultiSelect.stories.mdx
> +## Component Props for MultiSelect Listbox type
Remove `type` from this heading.

2023-01-25 22:07 UTC, bigfishdesign13 commented on src/components/MultiSelect/MultiSelect.stories.mdx
> +## Component Props for MultiSelect Dialog type
Remove `type` from this heading.

2023-01-25 22:07 UTC, bigfishdesign13 commented on src/components/MultiSelect/MultiSelect.stories.mdx
> +The `MultiSelect` type `listbox` leverages `downshift.js` to assist with
Remove `type` from this sentence.

2023-01-25 22:07 UTC, bigfishdesign13 commented on src/components/MultiSelect/MultiSelect.stories.mdx
> +The `MultiSelect` type `dialog` looks similar to the Listbox type, but because
Change this line to the following:
The `MultiSelect` `dialog` looks similar to the `MultiSelect` `listbox`, but because

2023-01-25 22:07 UTC, bigfishdesign13 commented on src/components/MultiSelect/MultiSelect.stories.mdx
> +If choosing the `type = 'dialog'` you can also add a second level of child items, in the following format:
Change this line to the following:
If you are using `type = 'dialog'`, you can also add a second level of child items in the following format:

2023-01-25 22:07 UTC, bigfishdesign13 commented on src/components/MultiSelect/MultiSelectMenuButton.tsx
> +  /** The labelText of the MultiSelect using this button. */
Minor adjustment:
```
The label text rendered within the MultiSelect using this button.
```

2023-01-26 15:28 UTC, bigfishdesign13 approved these changes
Looks good!

2023-01-26 15:31 UTC, merged