DSD-1336: Updating aria labels for Tabs mobile next/prev buttons
NYPL/nypl-design-system pull request #1281
Opened 2023-03-24 15:31 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-1336](https://jira.nypl.org/browse/DSD-1336)

## This PR does the following:

- Updates the `aria-label` for the previous/next buttons to "Scroll tabs left" and "Scroll tabs right", respectively, for better description.

## How has this been tested?

Locally.

## Accessibility concerns or updates

- Better descriptive text for the previous/next button.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2023-03-27 16:55 UTC, bigfishdesign13 requested changes
One additional change.

2023-03-27 16:55 UTC, bigfishdesign13 commented on src/components/Tabs/Tabs.tsx
> +          aria-label="Scroll tabs left"
Looking at this update, I feel we should also add a more descriptive `title` prop on the `Icon` components.  Can you also add `title="left arrow"` and `title="right arrow"` to the respective `Icon` components?

2023-03-28 15:47 UTC, bigfishdesign13 requested changes
One more small change.

2023-03-28 15:47 UTC, bigfishdesign13 commented on src/components/Tabs/Tabs.tsx
> +            title="left arrow"
I originally asked for the Icons to be titled "left arrow" and "right arrow", but I think what you accidentally did for the Next button works better.  With that, change this to "previous arrow."

2023-03-30 15:14 UTC, bigfishdesign13 approved these changes
The labeling updates look good, but did the updates in `ci.yml` do whay was expected?

2023-03-30 16:27 UTC, EdwinGuzman commented
> The labeling updates look good, but did the updates in ci.yml do whay was expected?

Yes? Sort of.

2023-03-30 17:01 UTC, merged