DSD-1334: Updating DOM so that the tooltip is accessible on every breadcrumb link
NYPL/nypl-design-system pull request #1283
Opened 2023-03-27 21:12 UTC by EdwinGuzman

POC for [DSD-1334](https://jira.nypl.org/browse/DSD-1334).

- This updates the DOM so that the `Tooltip` component wraps every link in the `Breadcrumbs` component. This adds the `aria-describe` appropriately to the anchor element to fix the a11y issue.
- This also updates the last item in the `Breadcrumbs` from a span to an anchor. This is behaviorally different but stylistically the same as before. Someone needs to approve this update or go back and rework this to decide if we still want this last item in the `Breadcrumbs`.

2023-03-27 21:20 UTC, EdwinGuzman commented
Will fix/update unit tests later once we come to an agreement on the next steps.

2023-04-12 15:05 UTC, isastettler approved these changes
Looks good.

2023-04-14 20:24 UTC, bigfishdesign13 requested changes
Overall, the changes look good, but let's also remove the hover color change for the current page link.

2023-04-20 14:44 UTC, EdwinGuzman commented
Updated.

2023-04-24 19:20 UTC, bigfishdesign13 commented
@EdwinGuzman The latest update looks good on everything except the `Blogs` color variant.

2023-04-24 21:36 UTC, EdwinGuzman commented
@bigfishdesign13 updated.

2023-04-25 14:54 UTC, bigfishdesign13 commented
@EdwinGuzman OK, you're goping to hate me.  The same hover color issues are also happening in dark mode.  Sorry, I was not checking that initially.

2023-04-25 16:07 UTC, EdwinGuzman commented
@bigfishdesign13 updated

2023-04-25 18:35 UTC, bigfishdesign13 approved these changes
Looks great!

2023-04-25 20:23 UTC, merged