DSD-1405: Adds Audio/Video Accessibility Guide
NYPL/nypl-design-system pull request #1299
Opened 2023-04-18 19:44 UTC by oliviawongnyc

Fixes JIRA ticket xxx

## This PR does the following:

- Adds `Audio and Video` page to the `Accessibility Guide` section of Storybook.
- Removes 'prettier/react' config as it has been merged into the 'prettier' config and was giving me a linter error. See here for details: https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21.

## How has this been tested?

- Locally, in Storybook.

## Accessibility concerns or updates

- None.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2023-04-20 15:37 UTC, EdwinGuzman requested changes
This is great, thanks. The only request is to add a "Resources" section at the end with links to accessibility standards or further information.

2023-04-24 15:21 UTC, bigfishdesign13 commented
@oliviawongnyc 

Use the following for the `Resources` section:
- [W3C Making Audio and Video Media Accessible](https://www.w3.org/WAI/media/av/)
- [W3C Audio & Video Media: Captions/Subtitles](https://www.w3.org/WAI/media/av/captions/)
- [W3C Audio & Video Media: Transcript](https://www.w3.org/WAI/media/av/transcripts/)

2023-04-24 19:25 UTC, bigfishdesign13 approved these changes
Looks good!

2023-04-25 13:40 UTC, EdwinGuzman approved these changes

2023-04-25 13:40 UTC, merged