DSD-1420: AudioPlayer in Storybook 7
NYPL/nypl-design-system pull request #1310
Opened 2023-05-01 23:01 UTC by bigfishdesign13

Fixes JIRA ticket [DSD-1420](https://jira.nypl.org/browse/DSD-1420)

## This PR does the following:

- Updates the story for the `AudioPlayer` component to work in Storybook 7.

## How has this been tested?

- local Storybook

## Accessibility concerns or updates

- n/a

### Checklist:

- [x] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [x] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2023-05-02 22:14 UTC, EdwinGuzman requested changes
Minor updates.

2023-05-02 22:14 UTC, EdwinGuzman commented on src/components/AudioPlayer/AudioPlayer.stories.tsx
> + * Main Story for the Accordion component. This must contains the `args`
Update `Accordion` with `AudioPlayer`.

2023-05-02 22:14 UTC, EdwinGuzman commented on src/components/AudioPlayer/AudioPlayer.stories.tsx
> +    audioType: {},
Can you make this control a radio type with the four string types? That's how the current Controls displays this prop and the set of four values.

2023-05-02 22:14 UTC, EdwinGuzman commented on src/components/AudioPlayer/AudioPlayer.stories.tsx
> +// The following are additional Accordion example Stories.
Updating `Accordion` text.

2023-05-04 18:36 UTC, EdwinGuzman approved these changes
The four option update doesn't work but it doesn't work in production so technically this is still the same as before.

2023-05-04 19:02 UTC, bigfishdesign13 commented
> The four option update doesn't work but it doesn't work in production so technically this is still the same as before.

@EdwinGuzman On its own, no, it looks like this prop is not working.  But it is.  There is validation that ensures that the embed code matches the 3rd party service specified in the `audioType` prop.  If you change this prop and then update the embed code with the corresponding code snippet, the audio player renders as expected.  I was confused by this at first myself.

2023-05-09 20:14 UTC, merged