DSD-1458: Styleguide docs to storybook7
NYPL/nypl-design-system pull request #1328
Opened 2023-05-10 20:32 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-1458](https://jira.nypl.org/browse/DSD-1458)

## This PR does the following:

- Updates all Styleguide docs to Storybook 7 version.
- Please take a close look at all the doc pages especially the "Colors" one which had additional bug fixes.
- An example production page: https://nypl.github.io/nypl-design-system/reservoir/v1/?path=/story/style-guide-bidirectionality--page

Bug fixes:
- There was a color name typo in the theme object which did not allow the color to render properly.

<img width="1936" alt="Screen Shot 2023-05-10 at 4 25 46 PM" src="https://github.com/NYPL/nypl-design-system/assets/1280564/cbbedba0-04cf-499b-ae98-9a128f9ecaab">

- Some props were not named correctly and _maybe_ did not render props correctly. @bigfishdesign13 let me know if the additional values in the table are correct. Otherwise, the data should be updated and removed. Specifically, this is for the `ui.typography.heading` and `ui.typography.body` in `dark.ui.bg.page`, `dark.ui.bg.default`, `dark.ui.bg.hover`, and `dark.ui.bg.active`.

<img width="1937" alt="Screen Shot 2023-05-10 at 4 26 30 PM" src="https://github.com/NYPL/nypl-design-system/assets/1280564/7859564a-f781-408d-87e0-f110555d1829">

## How has this been tested?

Locally.

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2023-05-11 20:52 UTC, bigfishdesign13 requested changes
Some minor requests and some questions.

2023-05-11 20:52 UTC, bigfishdesign13 commented on .storybook/main.ts
> -    "../src/docs/Welcome.mdx",
Did you intend to remove this?

2023-05-11 20:52 UTC, bigfishdesign13 commented on src/components/StyleGuide/Bidirectionality.mdx
> +### \`dir\` HTML attribute
Ha!  I ran into a problem with this formatting in another story.  I took the easy way out and just removed the backticks.

2023-05-11 20:52 UTC, bigfishdesign13 commented on src/components/StyleGuide/ColorCard.tsx
> +            <Text fontWeight="medium" noSpace size="tag" color={textColor}>
Despite the `noSpace` prop, the top margin is still being applied.

2023-05-11 20:52 UTC, bigfishdesign13 commented on src/components/StyleGuide/ColorCard.tsx
> +        borderTop: "1px solid !important",
Ideally, the border should be applied to the bottom of the elements, as there should be a bottom border for the last row.  But that would mean you'll probably need to also add some styles for thead to ensure that the header row also has a bottom border.

2023-05-11 20:52 UTC, bigfishdesign13 commented on src/components/StyleGuide/Forms.mdx
>  # Forms
In the `Form Input Components` list, can you change `Dropdown` to `MultiSelect` and then re-alphabetize?

2023-05-11 20:52 UTC, bigfishdesign13 commented on src/components/StyleGuide/Iconography.mdx
>  | Values for Examples Above |
I just realized that the nice table formatting is gone.  Do you know we can get that back?  Do we need to add our own styles?

2023-05-12 14:23 UTC, EdwinGuzman commented
I need to make another round of updates because I worked on getting the table to look right in the `ColorCard` table that it messes with table styles on all other storybook doc pages.

2023-05-23 20:33 UTC, EdwinGuzman commented
Latest update should cover all feedback updates.

2023-05-23 21:46 UTC, bigfishdesign13 approved these changes
Looks great.

2023-05-23 22:23 UTC, merged