DSD-1494 & DSD-1495: "connect" section colors and Breadcrumbs variant
NYPL/nypl-design-system pull request #1366
Opened 2023-06-12 18:31 UTC by bigfishdesign13

Fixes JIRA ticket [DSD-1494](https://jira.nypl.org/browse/DSD-1494) & [DSD-1495](https://jira.nypl.org/browse/DSD-1495)

## This PR does the following:

- Adds the `"connect"` section hues to the light and dark color palettes.
- Adds the `"connect"` color variant to the `Breadcrumbs` component.

## How has this been tested?

- local build of Storybook

## Accessibility concerns or updates

- The new "connect" colors and color combinations were vetted for a11y compliance.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2023-06-12 21:55 UTC, EdwinGuzman commented on src/theme/foundations/colors.ts
> +const connectPrimary = "#737373";
Just curious, why are these two gray-ish colors not based on the existing gray color palette?

2023-06-12 21:56 UTC, EdwinGuzman requested changes
Just a minor update to update the comment.

2023-06-12 21:56 UTC, EdwinGuzman commented on src/theme/foundations/colors.ts
> +    /** Books and More is used for the Catalog, Staff Picks, Recommendations,
The comment should be updated.

2023-06-13 15:00 UTC, bigfishdesign13 commented on src/theme/foundations/colors.ts
> +const connectPrimary = "#737373";
In a way, they are branded colors.  They were selected by the creative director.

2023-06-13 17:47 UTC, EdwinGuzman approved these changes

2023-06-13 17:55 UTC, merged