DSD-1304: Managing focus docs
NYPL/nypl-design-system pull request #1377
Opened 2023-06-30 14:39 UTC by oliviawongnyc

Fixes JIRA ticket [DSD-1304](https://jira.nypl.org/browse/DSD-1304). I will be sending this to Clare for review as well.

## This PR does the following:

- Adds `Managing Focus` page to the `Accessibility Guide` in Storybook.

## How has this been tested?

- In Storybook.

## Accessibility concerns or updates

- None.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2023-07-03 14:49 UTC, EdwinGuzman requested changes
Just a few minor updates but overall looks good!

2023-07-03 14:49 UTC, EdwinGuzman commented on src/components/AccessibilityGuide/ManagingFocus.mdx
> +includes interactive elements like links, checkboxes, and text inputs (though you
I think you can reword this so that the part in parenthesis is now. You already mentioned "by default" so it should be fine to break it up into another sentence. Maybe something like `"By default, this includes interactive elements like links, checkboxes, and text inputs, etc. It's possible to make any element focusable; but more on this later."

2023-07-03 14:49 UTC, EdwinGuzman commented on src/components/AccessibilityGuide/ManagingFocus.mdx
> +The `tabindex` attribute (`tabIndex` in React) can be used to manipulate the tab sequence of
"The `tabindex` HTML attribute ..."

2023-07-03 14:49 UTC, EdwinGuzman commented on src/components/AccessibilityGuide/ManagingFocus.mdx
> +natural focus order and therefore should be avoided.
Maybe add an explicit "Do _not_ use a `tabindex` value of 1 or greater."

2023-07-03 14:49 UTC, EdwinGuzman commented on src/components/AccessibilityGuide/ManagingFocus.mdx
> +focus to an element (as in the situations described above), use the `.focus()` method on the
Can you give an example of each? For example,
```
document.getElementByID("#element-to-focus").focus()
// and
focusRef.current.focus()
```
with more code is better such as `const focusRef = ...`.

2023-07-03 16:32 UTC, bigfishdesign13 requested changes
One minor change.

2023-07-03 16:32 UTC, bigfishdesign13 commented on src/components/AccessibilityGuide/ManagingFocus.mdx
> +Focusable elements are those that a keyboard user can navigate to. By default, this
Change `those` to `UI elements`.

2023-07-06 20:56 UTC, EdwinGuzman approved these changes

2023-07-07 18:48 UTC, bigfishdesign13 approved these changes
Looks good.

2023-07-07 18:59 UTC, merged