DSD-1326: Adding backdropBackgroundColor prop for campaign Hero component
NYPL/nypl-design-system pull request #1390
Opened 2023-08-04 14:27 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-1326](https://jira.nypl.org/browse/DSD-1326)

## This PR does the following:

- For the `"campaign"` `Hero` variant, an additional prop `backdropBackgroudColor` is configured to set the backdrop to an image or a color. Only the `"campaign"` variant can use this prop and will be ignored otherwise.

## How has this been tested?

Locally and through examples in Storybook.

## Accessibility concerns or updates

- N/A but we should be aware that devs _could_ set terrible color schemes that don't look right or are bad in contrast and we cannot readily prevent that.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2023-08-08 17:17 UTC, bigfishdesign13 requested changes
The new prop works well.  This just needs some adjustments to the docs.

2023-08-08 17:17 UTC, bigfishdesign13 commented on src/components/Hero/Hero.mdx
> +foreground settings in action.
This paragraph should also mention `foregroundColor`.  And maybe mention that we understand that the prop usage is a little confusing.

2023-08-08 17:17 UTC, bigfishdesign13 commented on src/components/Hero/Hero.stories.tsx
> +          backgroundColor="#A03E31"
Set this to a light color and then use the `foregroundColor` prop to set the text color to a dark color.

2023-08-08 17:17 UTC, bigfishdesign13 commented on src/components/Hero/Hero.tsx
> +        // ...rest
Should this be removed?

2023-08-10 14:26 UTC, EdwinGuzman commented on src/components/Hero/Hero.tsx
> +        // ...rest
Yes, though it breaks our convention of component props. I think because we are strictly controlling this component, we can and should remove this.

2023-08-10 14:53 UTC, EdwinGuzman commented
Updated

2023-08-10 19:42 UTC, bigfishdesign13 commented on src/components/Hero/Hero.stories.tsx
> +          foregroundColor="black"
This looks great!

2023-08-10 19:42 UTC, bigfishdesign13 approved these changes
The updates look great.

2023-08-11 14:01 UTC, merged