DSD-1671: Accessibility update for the focus ring style in the FeedbackBox open button
NYPL/nypl-design-system pull request #1501
Opened 2024-01-24 19:48 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-1671](https://jira.nypl.org/browse/DSD-1671)

## This PR does the following:

- Updates the focus ring style for the `FeedbackBox`'s open button to have better contrast against darker backgrounds.
- This specifically fixes the color contrast issue when reviewed in DC Facelift but this applied to other apps.

## How has this been tested?

Added a scrollable section in Storybook to better view the focus ring on various DS background colors.

## Accessibility concerns or updates

- Fixes the color contrast issue.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2024-01-29 21:33 UTC, bigfishdesign13 requested changes
The styles look good, but I have some comments about the docs.

2024-01-29 21:33 UTC, bigfishdesign13 commented on src/components/FeedbackBox/FeedbackBox.stories.tsx
> +        }}
Did you add this to move the button out so we could see the focus ring around the entire button?  I don't think this is necessary.  Let's just show the true positioning.

2024-01-29 21:33 UTC, bigfishdesign13 commented on src/components/FeedbackBox/FeedbackBox.stories.tsx
> +        </Heading>
We can change the background color using the feature in Storybook.  But this does work well on the `Docs` page, so let's keep it.  Just add a note that explains what's going on.

2024-01-30 17:50 UTC, bigfishdesign13 approved these changes
Looks great!

2024-01-30 22:04 UTC, EdwinGuzman commented
@avertrees @7emansell just fyi that I'm going to merge this in soon.

2024-01-31 18:03 UTC, merged