Dsd 1766/npm package update
NYPL/nypl-design-system pull request #1580
Opened 2024-04-12 21:27 UTC by EdwinGuzman

Fixes JIRA ticket xxx

## This PR does the following:

-

## How has this been tested?

## Accessibility concerns or updates

-

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2024-04-16 21:13 UTC, EdwinGuzman commented on src/components/MultiSelect/MultiSelect.test.tsx
> +describe.skip("MultiSelect Accessibility", () => {
Edwin: review.

2024-04-18 13:43 UTC, EdwinGuzman commented on .storybook/preview.tsx
> -      h1: ({ children }) => (
With the update in `.storybook/preview-body.html`, we can remove the DS overrides. They were mostly for styling but it previously did not allow us to use the id hash linking from headings. This is now done automatically by Storybook in their links and headings and the update in `.storybook/preview-body.html` just updates the font family for consistent styling.

2024-04-18 13:45 UTC, EdwinGuzman commented on src/components/Logo/LogoSvgs.tsx
> +import appleAppStoreBlack from "../../../icons/svg/logo-apple-app-store-black.svg";
Now possible with the updated `vite-plugin-svgr` package.

2024-04-18 16:11 UTC, bigfishdesign13 requested changes
I did a thorough spot check and overall it looks good.  However, the heading styles need some work.  I also had a few minor questions.

2024-04-18 16:11 UTC, bigfishdesign13 commented on package.json
> +    "typescript": "4.9.5"
Why is this included here and in `peerDependencies`?

2024-04-18 16:11 UTC, bigfishdesign13 commented on src/components/Accordion/Accordion.stories.tsx
> -import { withDesign } from "storybook-addon-designs";
By including this package as a dependency, it no longer needs to be explicitly imported into each story file?

2024-04-18 16:11 UTC, bigfishdesign13 commented on src/components/StyleGuide/Typography.mdx
> +#### Recommended Options
:)

2024-04-18 16:11 UTC, bigfishdesign13 commented on .storybook/preview-body.html
> +  .sbdocs h1:not(.chakra-heading.innerZoomElementWrapper h1) {
The `not` statement needs to be updated.  These styles are now impacting the styles of the DS `Heading` components used on the story pages.  Take a look at the `Heading` component story page.

2024-04-19 19:08 UTC, EdwinGuzman commented on package.json
> +    "typescript": "4.9.5"
Good point, this should actually go in "devDependencies". We shouldn't require apps that don't use typescript to import typescript.

2024-04-19 19:09 UTC, EdwinGuzman commented on src/components/Accordion/Accordion.stories.tsx
> -import { withDesign } from "storybook-addon-designs";
That's sort of true. The new stable npm package is now an official plugin so it's added in `.storybook/main.ts` as a global configuration.

2024-04-19 20:04 UTC, EdwinGuzman commented on package.json
> +    "typescript": "4.9.5"
Leaving this here and in `peerDependencies`. We need it for the Storybook build but not the React library build.

2024-05-06 16:42 UTC, EdwinGuzman commented
@bigfishdesign13 @7emansell @oliviawongnyc @jackiequach please review this soon if possible, thanks!

2024-05-06 17:01 UTC, 7emansell approved these changes
Lgtm from the storybook pages i spot checked

2024-05-06 18:00 UTC, jackiequach requested changes
Chakra Exports > Layout component pages have not been updated to use the `of` prop.

I think these are unrelated:
- Checkbox: some table of contents items are not linking to anything
- SearchBar: 
   - component props descriptions are not shown
   - [Autocomplete SearchBar](https://nypl-design-system-git-dsd-1766-npm-package-update-nypl.vercel.app/?path=%2Fdocs%2Fcomponents-form-elements-searchbar--docs) is misaligned 
- StructuredContent: component props not shown
- I'm seeing some slowness (locally) when going into doc pages, which seems to stem from the tests for the component running on load.

2024-05-06 18:00 UTC, jackiequach commented on src/components/Hero/Hero.stories.tsx
Not sure what the issue is, but when on the Storybook page for Hero there are a bunch of errors 
![image](https://github.com/NYPL/nypl-design-system/assets/37321861/47a05aca-4a55-4b6e-9f0d-7302962679d1)

2024-05-09 19:41 UTC, EdwinGuzman commented
@jackiequach thanks! Good catch on all the issues. Some were things we missed, most likely in the react 18/charka 2.8 upgrade. Everything you flagged should be fixed except for:

> I'm seeing some slowness (locally) when going into doc pages, which seems to stem from the tests for the component running on load.

Is it all doc pages or some?

2024-05-09 19:47 UTC, EdwinGuzman commented
Also, the autocomplete `SearchBar` example has not been working for a very long time. We'll have to fix that some time soon but not right now.

2024-05-09 20:58 UTC, jackiequach approved these changes
The changes look good. The slowness was across all components when I tested locally.

2024-05-10 21:36 UTC, EdwinGuzman commented
> The changes look good. The slowness was across all components when I tested locally.

Yes, and it was related to the local test json file. It was so slow when I initially tested and it was quite annoying. I did not really change anything and then it was running faster for me.

2024-05-16 17:24 UTC, bigfishdesign13 approved these changes
Looks good!

2024-05-16 17:24 UTC, bigfishdesign13 commented on src/components/Checkbox/Checkbox.mdx
> -- {<Link href="#error-text" target="_self">Error Text</Link>}
Good call replacing this!

2024-05-16 17:24 UTC, bigfishdesign13 commented on src/docs/Chakra.mdx
> +**Note**: These components are harder to have snapshot tests for because, internally,
Let's make sure to create a ticket to start replacing these notes and warnings with the `Banner` component.

2024-06-04 15:24 UTC, merged