Modal docs update
NYPL/nypl-design-system pull request #1612
Opened 2024-05-31 18:05 UTC by 7emansell

No ticket

## This PR does the following:

- Goal is to improve the Modal docs 

## How has this been tested?

## Accessibility concerns or updates

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2024-06-04 15:10 UTC, 7emansell commented
@bigfishdesign13 First pass, the section I added is a response to what I always get questions about/mess up in my own code

2024-06-04 15:34 UTC, EdwinGuzman approved these changes

2024-06-04 18:21 UTC, bigfishdesign13 requested changes
Right now, is see one small change that is needed.  But what about the concerns that Vera had when she was trying to implement the updated `Modal` component?  Do we need to make additional changes based on her experience?  Do we need to be more explicit about how the props should be used/combined?  Should the required props for each variant be made clearer?

2024-06-04 18:21 UTC, bigfishdesign13 commented on src/components/Modal/Modal.mdx
> +Action button: [Confirm]
Let's change this to match our newly suggested patterns.
```
Action buttons: [Cancel] [Confirm]
```

2024-06-06 20:16 UTC, bigfishdesign13 approved these changes
Looks good!

2024-06-07 14:14 UTC, merged