DSD-1795: Breadcrumbs Digital Collections variant
NYPL/nypl-design-system pull request #1629
Opened 2024-06-26 13:22 UTC by 7emansell

Fixes JIRA ticket [DSD-1795](https://newyorkpubliclibrary.atlassian.net/browse/DSD-1795).

## This PR does the following:

- Adds the `digitalCollections` color variant for `Breadcrumbs` component

## How has this been tested?

## Accessibility concerns or updates

### Checklist:

- [x] I have updated the Storybook documentation accordingly.
- [x] I have added relevant accessibility documentation for this pull request.
- [x] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2024-06-26 14:12 UTC, EdwinGuzman requested changes
This looks good but look at the `blogs` variant and the `customFocusColor ` function and how it handles its focus outline color. It's currently white on a light background and it won't pass accessibility reviews:
![Screenshot 2024-06-26 at 10 10 16 AM](https://github.com/NYPL/nypl-design-system/assets/1280564/cb1e80b2-17c9-4b8b-8b81-045caec84e7c)

2024-06-26 14:30 UTC, bigfishdesign13 requested changes
Looking good.  This just needs a couple of adjustments.

2024-06-26 14:30 UTC, bigfishdesign13 commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +  "digitalCollections",
Alphabetize this option with the others.

2024-06-26 14:30 UTC, bigfishdesign13 commented on src/components/Breadcrumbs/Breadcrumbs.stories.tsx
> +      </Box>
To keep the full list alphabetized. move this example between `Connect` and `Education`.

2024-06-26 14:30 UTC, bigfishdesign13 commented on src/theme/components/breadcrumb.ts
> +const digitalCollections = defineStyle({
Edwin already mentioned this, but take a look at how `customFocusColor` is used for the `blogs` variant.  The light background color necessitates a dark forcus ring.

2024-06-26 17:18 UTC, EdwinGuzman approved these changes

2024-06-27 21:52 UTC, bigfishdesign13 approved these changes
Looks good.  Just alphebatize the items in the array before you merge.

2024-06-27 21:52 UTC, bigfishdesign13 commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +  "digitalCollections",
This still needs to be alphabetized in the array.

2024-06-28 14:40 UTC, 7emansell commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +  "digitalCollections",
Oops thank you!!

2024-06-28 15:00 UTC, merged