DSD-1797: Breadcrumbs custom link prop
NYPL/nypl-design-system pull request #1643
Opened 2024-07-29 18:04 UTC by 7emansell

Fixes JIRA ticket xxx

## This PR does the following:

-

## How has this been tested?

-

## Accessibility concerns or updates

-

### Accessibility Checklist

- [ ] Checked Storybook's "Accessibility" tab for color contrast and other issues.
- [ ] The feature works with keyboard inputs including tabbing back and forward and pressing space, enter, arrow, and esc keys.
- [ ] For hidden text or when `aria-live` is used, a screenreader was used to verify the text is read.
- [ ] For features that involve UI updates and focusing on DOM `ref`s, focus management was reviewed.
- [ ] The feature works when the page is zoomed in to 200% and 400%.

## Open Questions

-

### Checklist:

- [ ] I have updated the Storybook documentation and changelog accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2024-08-01 15:23 UTC, EdwinGuzman requested changes
Looks good but some documentation update. I haven't tested it beyond that time we tested it together and it was working but I'll try to review it in Turbine or DCF if you have a working branch/vercel preview.

2024-08-01 15:23 UTC, EdwinGuzman commented on src/components/Breadcrumbs/Breadcrumbs.mdx
> +The `customLink` prop allows apps with internal routers (Next.js, for example) to pass their custom link component into Breadcrumbs so the links can use client-side routing.
nit: "into the `Breadcrumbs` component so ...."

2024-08-01 15:23 UTC, EdwinGuzman commented on src/components/Breadcrumbs/Breadcrumbs.mdx
> +To maximize these benefits, the `linkProps` prop on `breadcrumbsData` allows accompanying custom props on a link-by-link basis.
> To maximize these benefits,

I think I know what you're trying to say but you mentioned client-side routing and I'm assuming that's a benefit. I think you can add one or two more benefits or go into why client-side routing is beneficial in an app before this sentence.

2024-08-01 15:23 UTC, EdwinGuzman commented on src/components/Breadcrumbs/Breadcrumbs.mdx
> +Note: assigning a value for `href` in `linkProps` will override the `url` prop, so avoid this.
We try to include "recommend" in these types of notes so how about, ", ... we strongly recommend against this." or something along those lines.

2024-08-01 15:23 UTC, EdwinGuzman commented on src/components/Breadcrumbs/Breadcrumbs.mdx
> +<Breadcrumbs customLink={Link} breadcrumbsData={breadcrumbsData} />
At the top of this code example snippet, add the import for the `Link` component from next/link, to explicitly show where it's imported from.

2024-08-01 15:23 UTC, EdwinGuzman commented on src/components/Breadcrumbs/Breadcrumbs.mdx
> +To maximize these benefits, the `linkProps` prop on `breadcrumbsData` allows accompanying custom props on a link-by-link basis.
> accompanying custom props on a link-by-link basis

Can you also describe some examples and link to the nextjs link prop docs? You show it below in the code snippet but it'll be useful to say that it's really any prop that the framework's link component accepts.

2024-08-01 15:23 UTC, EdwinGuzman commented on src/components/Breadcrumbs/Breadcrumbs.tsx
> +  BreadcrumbLink,
Why the move?

2024-08-01 15:23 UTC, EdwinGuzman commented on src/components/Breadcrumbs/breadcrumbsChangelogData.ts
> +    notes: ["Adds `customLink` and `linkProps` props."],
Add why they're added or what it supports.

2024-08-01 17:22 UTC, 7emansell commented
> Looks good but some documentation update. I haven't tested it beyond that time we tested it together and it was working but I'll try to review it in Turbine or DCF if you have a working branch/vercel preview.

https://nypl-ds-test-b59lbu4si-nypl.vercel.app/components/breadcrumbs!

2024-08-01 21:16 UTC, EdwinGuzman approved these changes
Looks and works great. I'm debating whether `as` is a better prop name than `customLink`. `as` follows Chakra's convention and that's consistent.

There are various components that use the DS Link internally but I think only `Heading` and `Pagination` would benefit from using the nextjs link (from a quick glance). So if you were to add this feature to those components, would `as` or `customLink` work better?

I'm approving the functionality but updating the name is a small update.

2024-08-06 13:10 UTC, 7emansell commented
I feel like `customLink` is clearer to me as a dev than `as` (which even as a Chakra convention is slightly confusing) but I agree either could work, so happy to change it!

2024-08-06 18:35 UTC, jackiequach approved these changes
I think that the `customLink` prop makes sense here since `as` would imply the `Breadcrumbs` component is a `Link`, which is not true since it would be the children of the component would be links.

2024-08-08 19:01 UTC, bigfishdesign13 commented
@7emansell,
I don't think `as`, in this case, is appropriate.  As Jackie noted, it doesn't feel right as a component level prop name.  Something like `linkAs` would be better.  That said, I am leaning toward the other naming convention.  But I think even that could be better.  `customLinkType` or `customLinkComponent` feels better to me.

Cc @jackiequach @EdwinGuzman

2024-08-08 19:27 UTC, merged