DSD-1830: updating zindex in the FeedbackBox component
NYPL/nypl-design-system pull request #1665
Opened 2024-09-13 18:19 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-1830](https://newyorkpubliclibrary.atlassian.net/browse/DSD-1830)

## This PR does the following:

This issue was found in a Research Catalog page. In mobile, the `MultiSelect` components displayed above the `FeedbackBox` button and drawer components.

- This updates the z-index of the button but also Chakra's `Drawer` component. Their component, unfortunately, does not accept a class name or style props so the z-index rule is added as a global rule. This still has the same effect.
- This is difficult to test in Storybook because we don't have examples where we can easily add a `FeedbackBox` button on `MultiSelects` that makes sense. So perhaps a Turbine example is better.

## How has this been tested?

- Locally and in Research Catalog.

Issues fixed:
Button
![Screenshot 2024-09-10 at 11 10 45 AM](https://github.com/user-attachments/assets/dac94a32-bf1b-499c-819a-fc095b7d7d77)

Drawer
<img width="355" alt="Screenshot 2024-09-13 at 1 57 06 PM" src="https://github.com/user-attachments/assets/8f37b9c6-7d44-4efc-ae07-9558394c8460">

## Accessibility concerns or updates

-

### Accessibility Checklist

- [x] Checked Storybook's "Accessibility" tab for color contrast and other issues.
- [x] The feature works with keyboard inputs including tabbing back and forward and pressing space, enter, arrow, and esc keys.
- [x] For hidden text or when `aria-live` is used, a screenreader was used to verify the text is read.
- [x] For features that involve UI updates and focusing on DOM `ref`s, focus management was reviewed.
- [x] The feature works when the page is zoomed in to 200% and 400%.

## Open Questions

-

### Checklist:

- [x] I have updated the Storybook documentation and changelog accordingly.
- [x] I have added relevant accessibility documentation for this pull request.
- [x] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

[DSD-1830]: https://newyorkpubliclibrary.atlassian.net/browse/DSD-1830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-09-16 18:46 UTC, 7emansell approved these changes

2024-09-17 19:10 UTC, bigfishdesign13 requested changes
The layering issue is not totally fixed.  Please see my comment.

2024-09-17 19:10 UTC, bigfishdesign13 commented on src/theme/foundations/global.ts
> +  },
The button within the `MultiSelect` has a z-index of 10000, but it is showing above the `FeedbackBox` background.  It seems that the z-index of 1400 that is applied to the `FeedbackBox` popup element (the `role="dialog"` element)  is what is causing the problem.  And that value is coming from the `--nypl-zIndices-modal` CSS var.

<img width="605" alt="image" src="https://github.com/user-attachments/assets/28e38b98-48ab-48db-90ea-61142998b1fa">

2024-09-18 20:56 UTC, EdwinGuzman commented
Fixed in latest update: 
![Screenshot 2024-09-18 at 4 54 39 PM](https://github.com/user-attachments/assets/3c013751-6561-49fa-8c69-d3fbf0a36b92)

2024-09-19 15:59 UTC, bigfishdesign13 approved these changes
Very nice.

2024-09-23 15:34 UTC, merged