DSD-1871: Add item count to MultiSelect
NYPL/nypl-design-system pull request #1702
Opened 2024-11-13 16:32 UTC by jackiequach

Fixes JIRA ticket [DSD-1871](https://newyorkpubliclibrary.atlassian.net/browse/DSD-1871)

## This PR does the following:

- Adds `itemCount` data property to the `items` prop of `MultiSelect` to render the item count for the associated option.

## How has this been tested?

- Locally on Storybook

## Accessibility concerns or updates

- N/A

### Accessibility Checklist

- [ ] Checked Storybook's "Accessibility" tab for color contrast and other issues.
- [ ] The feature works with keyboard inputs including tabbing back and forward and pressing space, enter, arrow, and esc keys.
- [ ] For hidden text or when `aria-live` is used, a screenreader was used to verify the text is read.
- [ ] For features that involve UI updates and focusing on DOM `ref`s, focus management was reviewed.
- [ ] The feature works when the page is zoomed in to 200% and 400%.

## Open Questions

-

### Checklist:

- [ ] I have updated the Storybook documentation and changelog accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] Review the Vercel preview deployment once it is ready.

2024-11-14 18:35 UTC, bigfishdesign13 requested changes
This is great. It just needs one minor cosmetic update.

2024-11-14 18:35 UTC, bigfishdesign13 commented on src/components/MultiSelect/MultiSelect.tsx
> +          <Flex justify="space-between">
Add `gap="s"`.

2024-11-14 18:35 UTC, bigfishdesign13 commented on src/components/MultiSelect/MultiSelect.tsx
> +  itemCount?: number;
I like that this not allow something like `"8 items"` to be passed.

2024-11-14 20:54 UTC, bigfishdesign13 approved these changes
Looks great!

2024-11-15 20:31 UTC, EdwinGuzman reviewed
This works but before approving, did you try typing the `name` property in `MultiSelectItem` as `string | JSX.Element`? That's what I thought the approach would be since it's the same approach as the `Checkbox` component. That lets the consuming app handle pass the structured DOM themselves so the DS component is not responsible.

This approach give us more of the control which is okay, but just wondering if you tried the other approach and it didn't work.

2024-11-15 20:49 UTC, jackiequach commented
@EdwinGuzman I did not try the other approach. I think I misunderstood our conversation during planning. I implement the other approach for consistency.

2024-11-18 14:52 UTC, EdwinGuzman commented
@jackiequach no worries if you haven't already started doing so. This is a good approach and does make it easier (perhaps?) for consuming devs to pass in an additional property instead of managing the DOM themselves.

2024-11-18 14:52 UTC, EdwinGuzman approved these changes
Approved but don't merge just yet.

2024-11-25 17:07 UTC, merged