Link component update
NYPL/nypl-design-system pull request #339
Opened 2020-08-13 20:11 UTC by EdwinGuzman

Issue number: #309 #338

## **This PR does the following:**
- This updates the `Link` component to not render custom props in the generated anchor element, updates `linkType` to `type`, updates the stories with some explanations, adds an example using it with the Nextjs `Link` component, and implements `forwardRef` to use with other libraries.

### Front End Review:
- [ ] View [the example in Storybook]()

2020-08-13 20:12 UTC, EdwinGuzman commented on src/components/Accordion/Accordion.stories.tsx
> +    <li key="one">
Not strictly part of this PR but it bothered me seeing this warning every time Storybook opened.

2020-08-17 13:43 UTC, helenvholmes requested changes
These are some great updates, thanks Edwin. I pushed up some `<p>` tags and edited the wording on the NextJS link description (which, coincidentally, might mean that now it's incorrect—please check it).

Looks like the NextJS story is broken though, and I'm unclear on why—Link's `href` prop is optional but that's what it's throwing the error on.

2020-08-17 15:23 UTC, EdwinGuzman commented
@scooooooooby thanks for catching that. I updated the example with a better dummy/example "nextjs" wrapper that does a better job of cloning and properly rendering (even for an example) the `Link` component.

2020-08-17 15:35 UTC, helenvholmes approved these changes
Looks great!

2020-08-18 14:43 UTC, merged