Pagination should show correctly with fewer than 4 pages
NYPL/nypl-design-system pull request #506
Opened 2021-01-28 21:09 UTC by hokei

Fixes https://jira.nypl.org/browse/UX-234 and https://jira.nypl.org/browse/UX-230

## **This PR does the following:**
- The pagination component was showing strange behavior when there are fewer than 4 pages.  This has been fixed.  
<img width="234" alt="Screen Shot 2021-01-28 at 3 32 30 PM" src="https://user-images.githubusercontent.com/3579472/106199226-22f4a300-6183-11eb-8149-0beb364fd3ad.png">
<img width="299" alt="Screen Shot 2021-01-28 at 3 32 34 PM" src="https://user-images.githubusercontent.com/3579472/106199227-22f4a300-6183-11eb-872d-18793c012e04.png">
<img width="255" alt="Screen Shot 2021-01-28 at 3 32 38 PM" src="https://user-images.githubusercontent.com/3579472/106199229-22f4a300-6183-11eb-91d3-a5f0ec4e4bcd.png">

### Front End Review:
- [ ] View [the example in Storybook]()

2021-02-01 21:23 UTC, kaplanmichael requested changes
Looks good. The only issue I saw was that the focus outline sometimes gets cut off by the boundaries of the component:  
![image](https://user-images.githubusercontent.com/6432596/106519808-dde5af00-64a9-11eb-8438-01a64efbd1c9.png)

2021-02-01 21:23 UTC, kaplanmichael commented on src/components/Pagination/Pagination.tsx
> +    console.log("truncatedList", truncatedList);
Please remove `console.log`.

2021-02-01 22:09 UTC, hokei commented
> Looks good. The only issue I saw was that the focus outline sometimes gets cut off by the boundaries of the component
This looks like a bigger issue unrelated to pagination.  (Here's something similar in `Link`) 
<img width="588" alt="Screen Shot 2021-02-01 at 4 48 13 PM" src="https://user-images.githubusercontent.com/3579472/106524247-49cb1600-64b0-11eb-8d84-1463800b7a05.png">

I will file a ticket in the DS board

2021-02-02 15:31 UTC, kaplanmichael approved these changes
Cool, thanks for adding that ticket.  LGTM.

2021-02-02 16:16 UTC, merged