Dsd 103 mdx
NYPL/nypl-design-system pull request #514
Opened 2021-02-11 21:29 UTC by EdwinGuzman

Fixes [DSD-103](https://jira.nypl.org/browse/DSD-103)

## **This PR does the following:**
- Configures Storybook to be able to parse `.mdx` files so we can write stories in MDX. Storybook actually already configures it automatically but we overrode that configuration when we added our own webpack config with custom rules. So now the `config.module.rules` contains the mdx parsing config as well as the custom ones from `webpack.config.js`.
- This also includes a minor update to the storybook npm package and the `svg-inline-loader`.
- Added an introduction page to Storybook just to ✨ look nice ✨ .
- I "converted" three components to use MDX for stories.
  - `Accordion`
  - `Autosuggest`
  - `Button`
- There's actually a bug related to MDX showing code for stories and also using it's own component when it renders elements. This causes a bug I couldn't fix in the `Accordion` component (more here https://github.com/storybookjs/storybook/issues/11542). So, for the `Accordion` and `Autosuggest` there's a mix of the existing CSF-style story file along with an mdx file. This might seem like overkill but I think for those larger examples it's cleaner to separate the code with the documentation.
- Related to the above, something is wrong with the loaders and the MDX files can't completely parse Javascript/Typescript. But I think that can be worked on separately.
- The `Button` component is more straightforward.
- This allows us to move over to using Controls over Knobs much easier than before.

### Front End Review:
- [ ] View [the example in Storybook]()

2021-02-11 21:38 UTC, EdwinGuzman commented on src/components/Button/Button.tsx
> +/** Renders a simple `button` element with custom classes and modifiers. */
These comments before the component declaration are useful when we want to display them using the `Description` storybook component.

2021-02-18 20:25 UTC, EdwinGuzman commented
@hokei  @kaplanmichael @wluisi @siberry we went over the PR but let me know if the code needs any updates.

2021-02-18 21:24 UTC, kaplanmichael commented
> @hokei @kaplanmichael @wluisi @siberry we went over the PR but let me know if the code needs any updates.

@EdwinGuzman I'll test this myself also but wanted to confirm the working assumption that these storybook configurations won't currently break anything?

2021-02-18 21:47 UTC, EdwinGuzman commented
Correct, the stories don't affect how the components are compiled.  To test, I used `npm link` on this branch with the Library Card app and the components render and function the same.

2021-02-19 15:19 UTC, hokei commented on .storybook/main.js
> +    "../src/Intro.stories.mdx",
Can we put this under a /stories or /docs folder so that we don't have to add to this whenever we have new standalone stories?

2021-02-19 16:02 UTC, hokei commented on .storybook/main.js
> +    // We still want MDX-related rules. This is not ideal as the order of the
Nit:  I think it'll be more useful if this comment explicitly says
1) that rules[4] copies over the mdx specific rule, and will break if the mdx rule is moved
2) that custom webpack rules are mostly to handle SVG loading and that we may be able to use the default config if we fix SVG loading.  

I've seen so many webpack configs that I've been afraid to touch for fear of breaking it, and hopefully making it explicit why it is this way will give future people confidence that they can change it.

2021-02-19 16:52 UTC, EdwinGuzman commented
@hokei  updated the `main.js` file and added more documentation in the README as well. The `Intro.stories.mdx` file (or for other document-only stories), is now in the `/src/docs` directory.

2021-02-19 18:18 UTC, hokei approved these changes
LGTM

2021-02-19 20:00 UTC, kaplanmichael requested changes
I think this is a good approach.  On the outset, I don't see any red flags, but we may discover some issues once we're all working with this and trying to use it ourselves so we may revisit.  Thanks for doing this!

2021-02-19 20:00 UTC, kaplanmichael commented on README.md
> +When active developing components or fixing bugs, make sure that the related stories are created or updated. This means updating the respective `[component-name].stories.tsx` or `[component-name].sto
*active**ly**

2021-02-19 20:26 UTC, kaplanmichael approved these changes

2021-02-19 20:42 UTC, merged