Updating story for the Button component.
NYPL/nypl-design-system pull request #517
Opened 2021-02-19 20:10 UTC by EdwinGuzman

Fixes  [DSD-88](https://jira.nypl.org/browse/DSD-88)

## **This PR does the following:**
- Updates the story for the `Button` component to display patterns shown in the respective figma file.

### Front End Review:
- [ ] View [the example in Storybook]()

2021-02-19 20:12 UTC, EdwinGuzman commented
Do documentation-only PRs not trigger the netlify deployment action?

2021-02-22 22:04 UTC, hokei commented
Just checking - it eventually deployed right?  Or did you have to do something specific with it?

2021-02-22 22:08 UTC, EdwinGuzman commented
It eventually deployed. I'm not sure if this is related but I noticed that _this_ built when I created another PR.

2021-02-23 18:51 UTC, kaplanmichael requested changes
Looks good.  Just a few nits.

2021-02-23 18:51 UTC, kaplanmichael commented on src/components/Button/Button.stories.mdx
> +      attributes={{ style: { backgroundColor: "#d0343a" } }}
Please use color variable.

2021-02-23 18:51 UTC, kaplanmichael commented on src/components/Button/Button.stories.mdx
> +The "Back to Top" button should have secondary button styles and an up arrow icon.
The "Back to Top" button must be of type "Secondary" and must include an up arrow icon.

2021-02-23 20:44 UTC, kaplanmichael requested changes
One quick one and then good to go!

2021-02-23 20:44 UTC, kaplanmichael commented on src/docs/Intro.stories.mdx
>    foregroundColor="#ffffff"
Would you mind also adding  "--ui-white" instead of #ffffff ?

2021-02-24 14:27 UTC, kaplanmichael approved these changes

2021-02-24 14:28 UTC, merged