Breadcrumbs show up in light colors
NYPL/nypl-design-system pull request #528
Opened 2021-03-03 21:51 UTC by hokei

Fixes DSD-116

## **This PR does the following:**
- Breadcrumbs now have the dark-background link styling 

### Front End Review:
- [ ] View [the example in Storybook]()

2021-03-04 18:02 UTC, siberry approved these changes

2021-03-04 18:06 UTC, siberry requested changes
Unfortunately, on the storybook `.nypl-ds a:hover, .nypl-ds .link:hover` is overriding `.breadcrumbs__link:hover`

2021-03-08 16:59 UTC, hokei commented
@siberry Should work now.  
We're doing something a bit confusing in that sometimes we style via classname and sometimes we style via element.  In the BEM world the idea was that we were always styling via classname but I'm not sure if that's still the plan going forward.

2021-03-08 17:01 UTC, siberry approved these changes

2021-03-08 19:09 UTC, merged