DSD-180: StatusBadge Component Set Default Width
NYPL/nypl-design-system pull request #550
Opened 2021-05-03 20:35 UTC by nypl-wluisi

Jira ticket: https://jira.nypl.org/browse/DSD-180

## **This PR does the following:**
- Sets a default width of `fit-content` to StatusBadge component and adds more padding inside to match Figma. Previously, this component would just expand full width, but in all use cases in Figma, the component's width should match the width of the inner text.

### Front End Review:
- [ ] View [the example in Storybook]()

2021-05-07 21:03 UTC, kaplanmichael requested changes

2021-05-07 21:03 UTC, kaplanmichael commented on src/components/StatusBadge/_StatusBadge.scss
> +  width: fit-content;
A width of `fit-content` might not work properly on Firefox unless you use a vendor prefix.  Could you please verify that this looks good on FF (I'd do it myself but I am still trying to get a license for BrowserStack )

CC @bigfishdesign13

2021-05-10 14:17 UTC, kaplanmichael commented on src/components/StatusBadge/_StatusBadge.scss
> +  width: fit-content;
@wluisi Yeah, it looks like you'll probably need the browser prefix. Here's what it loox like on FF:
![image](https://user-images.githubusercontent.com/6432596/117673523-db65b600-b178-11eb-9b45-4a483424c8dc.png)

2021-05-10 14:25 UTC, nypl-wluisi commented on src/components/StatusBadge/_StatusBadge.scss
> +  width: fit-content;
@kaplanmichael Ok I can add that to this PR. For some reason I thought the DS was already using something like this? https://www.npmjs.com/package/autoprefixer -- for now, I'm fine with adding the prefixes manually to get this PR finished, but do you think we should create a ticket to add autoprefixing ?

2021-05-10 18:28 UTC, nypl-wluisi commented
@kaplanmichael I added the prefix for moz FF. Also, this is pre-existing, but we're setting the border radius with this:
```
border-radius: 4px;
```

Should this use a css var instead of hardcoding a specific px value?

2021-05-13 18:02 UTC, kaplanmichael commented on src/components/StatusBadge/_StatusBadge.scss
> +  width: fit-content;
That's funny--I had thought that we had an auto-prefixer as well.  I'll mention that to Marty and see if we can make that happen.

2021-05-13 18:08 UTC, kaplanmichael commented
> @kaplanmichael I added the prefix for moz FF. Also, this is pre-existing, but we're setting the border radius with this:
> 
> ```
> border-radius: 4px;
> ```
> 
> Should this use a css var instead of hardcoding a specific px value?

Yes, @wluisi if you wouldn't mind using ` --space-xxs`, that would be great!  Thanks!

2021-05-13 20:02 UTC, kaplanmichael approved these changes
LGTM

2021-05-13 20:18 UTC, merged