DSD-289: heading mdx story
NYPL/nypl-design-system pull request #568
Opened 2021-06-03 21:56 UTC by bigfishdesign13

Fixes DSD-289

## **This PR does the following:**
- Changes `Heading` story from `.tsx` to `.mdx`

### Front End Review:
- [ ] View [the example in Storybook]()

2021-06-07 20:45 UTC, hokei requested changes
Kind of same as all the other PRs:  Show the "basic" heading many times with different args in the "all headings" page, instead of creating a separate "all headings" story. Otherwise, looks great!

2021-06-10 21:16 UTC, hokei commented on src/components/Heading/Heading.stories.mdx
> +<Preview>
If you nest this all inside a div (like 

```
<Preview>
  <div>
    <Heading id="heading1" level={1} text="Heading 1" />
    <Heading id="heading2" level={2} text="Heading 2" />
    <Heading id="heading3" level={3} text="Heading 3" />
    <Heading id="heading4" level={4} text="Heading 4" />
    <Heading id="heading5" level={5} text="Heading 5" />
    <Heading id="heading6" level={6} text="Heading 6" />
  </div>
</Preview>
```

It will all appear on different lines.  

In the future also, you can make storybook-specific styles to overwrite storybook stuff.  
Like, if you went 
<Preview>
  <div className="sb-only-class"> 
     <Component />
  </div>
</Preview>


We should figure out how to not export these classes, but I think the only sb class that's left is in `card` and it's not actually being used.

2021-06-14 15:08 UTC, bigfishdesign13 commented on src/components/Heading/Heading.stories.mdx
> +<Preview>
Thanks for the suggestion.  Works great.

2021-06-14 15:10 UTC, bigfishdesign13 commented on src/components/Heading/Heading.stories.mdx
> +<Preview>
I made a note to myself to take a look at the Storybook-specific styles at some point.

2021-06-17 18:41 UTC, hokei approved these changes

2021-06-17 21:29 UTC, merged