List listItems data prop
NYPL/nypl-design-system pull request #597
Opened 2021-07-13 20:21 UTC by EdwinGuzman

Fixes [DSD-361](https://jira.nypl.org/browse/DSD-361)

## **This PR does the following:**
- This adds the ability to render a `List` component through an array of data instead of through children elements.
- The `listItems` prop is used to render the correct children elements.
- Instead of passing `li` elements for `ListType.Unordered` or ListType.Ordered` types, `listItems` takes an array of strings such as `["fish", "cat", "dog"]`.
- Instead of passing `dt` and `dd` elements for `ListType.Definition` type, `listItems` takes an array of objects, each containing `term` and `definition` keys  such as `[{ term: "fish", definition: "swims" }, { term: "cat", definition: "meows" }, { term: "dog", definition: "barks" }]`.

### Front End Review:
- [ ] View [the example in Storybook]()

2021-07-14 19:34 UTC, bigfishdesign13 requested changes
This looks great except for a few minor formatting issues.

2021-07-14 19:34 UTC, bigfishdesign13 commented on src/components/List/List.stories.mdx
> +// With `itemList` data prop
Example code needs to be cleaned up (missing commas and brackets).

2021-07-14 19:34 UTC, bigfishdesign13 commented on src/components/List/List.stories.mdx
> +## Lists with data props
Nit: match the captialization used in other stories

2021-07-14 19:34 UTC, bigfishdesign13 commented on src/components/List/List.stories.mdx
> +    name="List with data props"
Nit: match the captialization used in other stories

2021-07-15 14:12 UTC, EdwinGuzman commented
Good catches. Updated.

2021-07-16 15:17 UTC, bigfishdesign13 approved these changes
Looks good.

2021-07-16 21:16 UTC, merged

2021-07-19 13:40 UTC, bigfishdesign13 commented
@EdwinGuzman I just realized there was no entry in the CHANGELOG for this PR.  Let's make sure to get something in there befor the release on Thursday.