DSD-45 Documentation updates to the readme, pull request template, and the contributing files
NYPL/nypl-design-system pull request #603
Opened 2021-07-19 18:56 UTC by EdwinGuzman

Fixes [DSD-45](https://jira.nypl.org/browse/DSD-45)

## **This PR does the following:**
- Adds a `contributing` file and updates the `readme` and `pull request template` files to better outline and link to related information in the wiki.
- Also cleaning up existing documentation that is either no longer necessary or has changed in the past few weeks.

### Front End Review:
- [ ] View [the example in Storybook]()

2021-07-19 19:39 UTC, EdwinGuzman commented
Also went through the pages in the wiki and updated them where needed.

2021-07-20 16:56 UTC, bigfishdesign13 requested changes
These updates are awesome.  I left just a few comments about small things.

2021-07-20 16:56 UTC, bigfishdesign13 commented on .github/CONTRIBUTING.md
> +When creating a new React component or updating an existing one, you MUST follow the [Anatomy of a Component](https://github.com/NYPL/nypl-design-system/wiki/Anatomy-of-a-Component) wiki page documen
Typo in second sentense.
> This explains `the` all the files that...

2021-07-20 16:56 UTC, bigfishdesign13 commented on README.md
>  The NYPL Design System provides accessible stories, but real live data can necessitate additional accessibility requirements beyond what we're committed to in our generic, extensible components. To e
Metronome is now password protected.  Maybe add something like, "For access to Metronome, please contact..."

2021-07-21 14:10 UTC, hokei commented
this looks great to me!

2021-07-21 16:47 UTC, EdwinGuzman commented
Updated.

2021-07-21 19:05 UTC, bigfishdesign13 approved these changes
Looks good.

2021-07-21 21:14 UTC, merged