DSD-440: form spacing variants
NYPL/nypl-design-system pull request #651
Opened 2021-08-20 17:04 UTC by bigfishdesign13

Fixes JIRA ticket [DSD-440](https://jira.nypl.org/browse/DSD-440)

## This PR does the following:
- adds `FormSpacing` enum
- adds `spacing` prop to `Form` component

## How has this been tested?

- DS local build

### Checklist:

- [x] I have updated the Storybook documentation accordingly.
- [x] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2021-08-20 17:12 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr651-jrksmtutj1qb2jjv9ht2p2owihilhlbl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/611fe0ba378c5f45ca85d087

2021-08-20 17:57 UTC, EdwinGuzman commented on src/components/Form/Form.stories.mdx
> +    <>
This should be an `li`.

2021-08-20 18:01 UTC, EdwinGuzman requested changes
Just a minor update but everything else looks okay.

2021-08-20 18:41 UTC, bigfishdesign13 commented on src/components/Form/Form.stories.mdx
> +    <>
Yes.  Got catch.

2021-08-20 18:47 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr651-jrksmtutj1qb2jjv9ht2p2owihilhlbl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/611fe0ba378c5f45ca85d087

2021-08-23 22:12 UTC, EdwinGuzman approved these changes

2021-08-24 17:19 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr651-jrksmtutj1qb2jjv9ht2p2owihilhlbl.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/611fe0ba378c5f45ca85d087

2021-08-24 17:20 UTC, merged