DSD-199: RadioGroup component - part 2
NYPL/nypl-design-system pull request #664
Opened 2021-09-01 21:44 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-199](https://jira.nypl.org/browse/DSD-199)

## This PR does the following:
- Continues off from PR #661 
- This covers some concerns from the first PR and continues working through the Chakra refactor.
- Instead of using Chakra's own `RadioGroup` component, this uses other Chakra components and the style object to divide and appropriately set styles.
- Configures the `RadioGroup` component so it works with the DS `Radio` component.

## How has this been tested?

Locally in Storybook and linked in the Library Card app for uncontrolled and controlled forms states.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2021-09-01 21:45 UTC, EdwinGuzman commented
@bigfishdesign13 I think the `CheckboxGroup` component will follow a very similar pattern for the DS version.

2021-09-01 21:53 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr664-0kvlxsozcctnvucajhh11k9tdbasmv6o.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/612ff43208cf47be295af8ae

2021-09-02 14:28 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr664-0kvlxsozcctnvucajhh11k9tdbasmv6o.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/612ff43208cf47be295af8ae

2021-09-03 02:09 UTC, bigfishdesign13 requested changes
This looks really good and I am excited for it.  Just needs a few small changes.

2021-09-03 02:09 UTC, bigfishdesign13 commented on src/components/RadioGroup/RadioGroup.tsx
> +    React.Children.map(children, (child: React.ReactElement, i) => {
Can you add validation here to ensure that only DS `Radio` components are being passed?

2021-09-03 02:09 UTC, bigfishdesign13 commented on src/components/RadioGroup/RadioGroup.tsx
> +          spacing={spacing.s}
When `direction` is set to `row`, the spacing should be `2rem`, which aligns with `spacing.l`.

2021-09-07 14:29 UTC, EdwinGuzman commented
@bigfishdesign13 updated.

2021-09-07 14:38 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr664-0kvlxsozcctnvucajhh11k9tdbasmv6o.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/612ff43208cf47be295af8ae

2021-09-07 16:15 UTC, bigfishdesign13 reviewed
I think this looks good, but I will allow @nypl-wluisi or @hokei to give the final approval on this one.

2021-09-15 00:11 UTC, nypl-wluisi approved these changes
This looks good to me.

2021-09-15 13:48 UTC, bigfishdesign13 approved these changes
My official approval on the PR.

2021-09-15 15:49 UTC, merged