DSD-474: DS Select component with Chakra's Select component
NYPL/nypl-design-system pull request #683
Opened 2021-09-17 19:54 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-474](https://jira.nypl.org/browse/DSD-474)

## This PR does the following:
- Updates the DS `Select` component to use Chakra's `Select` component.
- The deprecated examples were removed.

## How has this been tested?

Locally and through Storybook.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2021-09-17 20:03 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr683-4ptrkz1hten1qaiftxgelpvngxpsxdw1.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6144f273b8fde51bddb0adb2

2021-09-17 22:04 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr683-4ptrkz1hten1qaiftxgelpvngxpsxdw1.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6144f273b8fde51bddb0adb2

2021-09-20 20:33 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr683-4ptrkz1hten1qaiftxgelpvngxpsxdw1.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6144f273b8fde51bddb0adb2

2021-09-20 21:17 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr683-4ptrkz1hten1qaiftxgelpvngxpsxdw1.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6144f273b8fde51bddb0adb2

2021-09-23 19:10 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr683-4ptrkz1hten1qaiftxgelpvngxpsxdw1.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6144f273b8fde51bddb0adb2

2021-09-23 19:36 UTC, bigfishdesign13 requested changes
Looks good and works well.  Just a few minor changes requested.

2021-09-23 19:36 UTC, bigfishdesign13 commented on src/components/Select/Select.stories.mdx
> +| Latest            | `0.24.2`   |
Shoiudl be changed to `0.25.1`.

2021-09-23 19:36 UTC, bigfishdesign13 commented on src/components/Select/Select.stories.mdx
> +children _need_ to be `option` HTML elements.
I was not sure what this meant at first.  Can you adjust the language to something like this?
```
The `Select` component renders all the necessary wrapping and associated text elements, but the select options _need_ to be child `<option>` HTML elements.
```

2021-09-24 16:32 UTC, EdwinGuzman commented
Updated.

2021-09-24 16:40 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr683-4ptrkz1hten1qaiftxgelpvngxpsxdw1.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6144f273b8fde51bddb0adb2

2021-09-24 20:09 UTC, bigfishdesign13 approved these changes
Looks good!

2021-09-24 21:11 UTC, merged