DSD-430: Using DS spacing values for the Heading component
NYPL/nypl-design-system pull request #691
Opened 2021-09-23 20:18 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-430](https://jira.nypl.org/browse/DSD-430)

## This PR does the following:
- Updating the "em" spacing values for the Heading component with proper Chakra NYPL-theme values.

## How has this been tested?

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2021-09-23 20:23 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr691-nlxj6vzp3jwhgqxwhdapxmqthelccscb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614ce117d7000ac44349b82b

2021-09-24 17:44 UTC, bigfishdesign13 requested changes
Just need to increase the spacing.

2021-09-24 17:44 UTC, bigfishdesign13 commented on src/theme/components/heading.ts
> +  marginBottom: 2, // var(--space-xs)
After seeing how this responded, this should be bumped up to `marginBottom: 4` to align with `--space-s`.

2021-09-24 18:30 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr691-nlxj6vzp3jwhgqxwhdapxmqthelccscb.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/614ce117d7000ac44349b82b

2021-09-24 20:17 UTC, bigfishdesign13 approved these changes
The changes look good!

2021-09-27 13:11 UTC, merged