WIP: DSD-501 & DSD-453: Chakra Image and prop refactor
NYPL/nypl-design-system pull request #703
Opened 2021-09-29 19:42 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-501](https://jira.nypl.org/browse/DSD-501) and [DSD-453](https://jira.nypl.org/browse/DSD-453)

## This PR does the following:
- *This is a work-in-progress to get a sense of it. There are things I want to clean up and add better comments/documentation but I'll do that after getting an initial reaction.*
- Updates the `Image` component to use Chakra.
- Updates/refactors its props.
- Moves styles to its CSS JS object.
- Updates its usage in the `Hero` and `Card` components.

Notes:
- `CardImage` is directly set to `Image`, but `CardImageSizes` and `CardImageRatios` were removed in favor of using `ImageSizes` and `ImageRatios`, respectively.
- There is still SCSS in the `Hero` and `Card` components that update the styling for the `Image` component.
- This was tricky and we probably don't have to do much until we refactor the `Card` component to use Chakra.
- For the `Hero` component, the image overrides already exist in its `hero.ts` CSS-theme JS object. Not much has to be done right now but it could be cleaner. For example, in the `campaign` variant:
```jsx
img: {
  flex: {
    base: "1 1 100%",
    md: "0 0 50%",
  },
  minWidth: "0", // https://github.com/philipwalton/flexbugs/issues/41
  objectFit: "cover",
  width: "100%",
  height: { md: "320px" },
},
```
maybe we can move this to the `image.ts` file as a hero campaign variant. I'm not sure what the best pattern is yet.
- The `Card` component _needs_ the image to be wrapped in divs with specific stylings but the `Hero` component does not need these div wrappers. In fact, it renders pretty badly. By default, the div wrappers are always rendered to make it easier to apply the size and aspect ratio. For the `Hero` component, however, the prop `useImageWrapper` is set to false so that only the `img` element is rendered with no div wrappers. This pattern works nicely but let me know what you think.

## How has this been tested?

Storybook. Check `Hero`, `Card`, and `Image`.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2021-09-29 19:50 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr703-euxm3uflqmmvpnpmpmjb5pn1fy8nndbw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6154c1a44807c048773e7871

2021-09-30 17:49 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr703-euxm3uflqmmvpnpmpmjb5pn1fy8nndbw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6154c1a44807c048773e7871

2021-09-30 19:18 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr703-euxm3uflqmmvpnpmpmjb5pn1fy8nndbw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6154c1a44807c048773e7871

2021-10-04 20:58 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr703-euxm3uflqmmvpnpmpmjb5pn1fy8nndbw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6154c1a44807c048773e7871

2021-10-14 21:15 UTC, bigfishdesign13 requested changes
It's working pretty well, but there are few things that we should discuss.

2021-10-14 21:15 UTC, bigfishdesign13 commented on src/components/Card/Card.tsx
> +export const CardImage = Image;
Now that `Card` is simply using `Image`, I think you can kill this altogether.  The placement and styling of the image within `Card` is very controlled, so we don't really want users to set their own image within the content area.

2021-10-14 21:15 UTC, bigfishdesign13 commented on src/components/Image/Image.tsx
> +    useImageWrapper = true,
We should control if and when this is set to `false`.  Rather than expecting the consuming app to do it.  It can default to `false` and then get flipped to `true` only when `imageAspectRatio` is set to anything other than `original`.  Those extra wrapper divs are only needed to control the image cropping.

2021-10-14 21:15 UTC, bigfishdesign13 commented on src/components/Image/Images.stories.mdx
> +| Latest            | `0.25.1`   |
Make sure to update to `0.25.2`.

2021-10-14 21:15 UTC, bigfishdesign13 commented on src/index.ts
> -export {
Make sure to add the exports for the new enums under `Image`.

2021-10-14 21:15 UTC, bigfishdesign13 commented on src/theme/components/image.ts
> +      height: "100%",
This 100% value is only necessary when the images are being cropped.  It is impacting the image aspect ratio when only the size is set.  Take a look at the Image Sizes story.  In fact, let's have a call to look at it together.

2021-10-20 16:40 UTC, EdwinGuzman commented on src/components/Image/Image.tsx
> +    useImageWrapper = true,
Remove this from the prop and use it internally when `imageAspectRatio` is not `Original`.

2021-10-20 16:54 UTC, EdwinGuzman commented on src/components/Card/Card.tsx
> +export const CardImage = Image;
This is updated in the `Card` PR #718  so will leave this as is here.

2021-10-20 20:59 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr703-euxm3uflqmmvpnpmpmjb5pn1fy8nndbw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6154c1a44807c048773e7871

2021-10-21 15:24 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr703-euxm3uflqmmvpnpmpmjb5pn1fy8nndbw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6154c1a44807c048773e7871

2021-11-01 22:39 UTC, EdwinGuzman commented
What else does this need to be merged in?

2021-11-01 23:07 UTC, bigfishdesign13 commented
> What else does this need to be merged in?

@EdwinGuzman I believe just validation of the last block of work I completed.  Do you want to take a look?  If it's good in your eyes, I'll approve the PR.

2021-11-02 13:42 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr703-euxm3uflqmmvpnpmpmjb5pn1fy8nndbw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6154c1a44807c048773e7871

2021-11-02 15:27 UTC, EdwinGuzman commented
@bigfishdesign13 did some minor cleanup but it looks good, thanks.

2021-11-02 15:52 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr703-euxm3uflqmmvpnpmpmjb5pn1fy8nndbw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6154c1a44807c048773e7871

2021-11-02 16:50 UTC, bigfishdesign13 approved these changes
Edwin and I have both put our stamp of approval on this one. 👍

2021-11-02 18:25 UTC, merged