WIP DSD-507: Using chakra for the SearchBar component
NYPL/nypl-design-system pull request #710
Opened 2021-10-01 16:16 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-507](https://jira.nypl.org/browse/DSD-507)

## This PR does the following:
- This is using the children component pattern and I'm wondering if it's better to use the prop pattern instead.
- There are some things I want to discuss before I proceed.
- Some updates are blocked by other components that should be updated first, such as `Form`.
- Creating a PR to see the Tugboat preview.

## How has this been tested?

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2021-10-01 16:23 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr710-2rl71du1ury5hwjjw4i8wivnudpjiyty.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6157346b4807c036654086fe

2021-10-04 20:55 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr710-2rl71du1ury5hwjjw4i8wivnudpjiyty.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6157346b4807c036654086fe

2021-10-05 20:17 UTC, EdwinGuzman commented
@bigfishdesign13 this is ready for a review now.

2021-10-05 20:23 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr710-2rl71du1ury5hwjjw4i8wivnudpjiyty.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6157346b4807c036654086fe

2021-10-06 21:23 UTC, bigfishdesign13 requested changes
This works well, but there are some changes that we should talk about.

2021-10-06 21:23 UTC, bigfishdesign13 commented on src/components/SearchBar/SearchBar.tsx
> +  helperErrorText?: string;
The data pattern in all other form components is to have separate `helperText` and `invalidText` (nee `errorText`) props.  Additionally, from a UI perspective, the error text always overwrites the helper text when `isInvalid` is `true`.

2021-10-06 21:23 UTC, bigfishdesign13 commented on src/components/SearchBar/SearchBar.tsx
> +  /** Populates aria-label on the form and labels the entire SearchBar. */
This prop only populates the `aria-label` on the form.  It does not create a visual label.  And as we are thinking about this, it shoud be noted that we have removed the `aria` props from all other form components and we are now relying on the component to properly generate the `aria` attributes based on other props.  Should we do the same here and follow the pattern of using `labelText` and `showLabel` props?

2021-10-06 21:23 UTC, bigfishdesign13 commented on src/components/SearchBar/SearchBar.tsx
> +        modifiers={["small", "icon-left"]}
Based on the recent updates to the `Icon` component, this need to be changed.  But I'm sure you already know this.

2021-10-06 21:23 UTC, bigfishdesign13 commented on src/components/SearchBar/SearchBar.tsx
> +  const helperErrorTextElem = helperErrorText && (
As I mentioned elsewhere, the UI pattern has been for the invalid text to overwrite the helper text when `isInvalid` is true.  Right now, the default invalid text in the `TextInput` is triggering when it is set as invalid, so we'll need to add a method to text the default error text to not show.  I believe we talked about this the other day.

2021-10-06 21:23 UTC, bigfishdesign13 commented on src/theme/components/select.ts
> +    searchbar: {
I would also like to address the right side border.  I have a query into Kathy about this, but I would like the right side border on the `Select` to be set to 0 and for the borde radius radius to also be set to 0.  Essentially, I would like it to be removed altogether and for the `Select` to appear attached to the `TextInput`.

2021-10-06 21:23 UTC, bigfishdesign13 commented on src/theme/components/select.ts
> +    searchbar: {
Similarly, this same type of customization and treatment should be applied to the `Button` in order to make it appear attached the `TextInput`.

2021-10-06 21:23 UTC, bigfishdesign13 commented on src/theme/components/textInput.ts
> +  variants: {
This gets a little more complicated here.  The border radius should be set to 0 on the edges that touch the other elements.  Which means, when the select field is not used, the border radius should not be changed.

2021-10-07 15:42 UTC, nypl-wluisi commented
@bigfishdesign13 @EdwinGuzman 
Can we make this iteration of the "Search Bar" handle a label ("Enter an address ...") above the input, like this?

<img width="764" alt="search-bar-label-above" src="https://user-images.githubusercontent.com/62392174/136418057-0ad29a33-f12a-42e3-8e73-07e9efc2560a.png">

I'd like to switch over to using the search bar from DS, but I need this layout on several different page types.

2021-10-07 16:12 UTC, EdwinGuzman commented
> Can we make this iteration of the "Search Bar" handle a label ("Enter an address ...") above the input, like this? 

Hmm I think this is a good candidate to say that it should be looked at by the UX team first, Figma should be updated, and then we'll make the update.

2021-10-07 16:19 UTC, EdwinGuzman commented on src/components/SearchBar/SearchBar.tsx
> +        modifiers={["small", "icon-left"]}
Yeah, I'll update this once the `Icons` PR is merged.

2021-10-07 17:01 UTC, EdwinGuzman commented on src/components/SearchBar/SearchBar.tsx
> +  /** Populates aria-label on the form and labels the entire SearchBar. */
Yes, I'll make this update but since we don't ever show the label, then maybe we can say that even though `labelText` is passed, it won't actually show up. So then we won't need the `showLabel` prop.

2021-10-07 17:07 UTC, EdwinGuzman commented on src/components/SearchBar/SearchBar.tsx
> +  const helperErrorTextElem = helperErrorText && (
We did but said it'd be a different ticket/PR for both the `Select` and `TextInput` components.

2021-10-07 17:07 UTC, bigfishdesign13 commented on src/components/SearchBar/SearchBar.tsx
> +  /** Populates aria-label on the form and labels the entire SearchBar. */
OK.  But looking at Bill's comment, adding heading and description elements seem to make more sense.  Similar to both how `VideoPlayer` is handled and how `Slideshow` will be handled.  So yes, add `labelText` for now and `showLabel` can be considered if/when the UX is updated.

2021-10-07 17:09 UTC, bigfishdesign13 commented
> Can we make this iteration of the "Search Bar" handle a label ("Enter an address ...") above the input, like this?

@nypl-wluisi That descriptor text could also go in as helper text.  That said, I do think the UI for the SearchBar component could be updated.  I'll get that rolling.

2021-10-07 17:16 UTC, nypl-wluisi commented
> > Can we make this iteration of the "Search Bar" handle a label ("Enter an address ...") above the input, like this?
> 
> @nypl-wluisi That descriptor text could also go in as helper text. That said, I do think the UI for the SearchBar component could be updated. I'll get that rolling.

Would it be the `<label>` element of the `<input>` ? We can confirm, but for accessibility, that's how I set it up.

2021-10-07 17:31 UTC, EdwinGuzman commented
Yes, it should be the `<label>` element for the `<input>` element. This gets trickier when there is a `<select>` component. Should the label be for the select or the input element? It'd get associated with the `form` element through the aria-label but I'm not sure what makes the most sense when there is a `select` as well, i.e. when you click on the label, where does the focus go to? We should have Zach review and give a recommendation.

2021-10-07 17:33 UTC, EdwinGuzman commented
@bigfishdesign13 updated.

2021-10-07 18:05 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr710-2rl71du1ury5hwjjw4i8wivnudpjiyty.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6157346b4807c036654086fe

2021-10-07 20:24 UTC, bigfishdesign13 commented on src/components/SearchBar/SearchBar.tsx
> +  const helperErrorTextElem = helperErrorText && (
Right.  Thanks for taking care of that.

2021-10-07 20:27 UTC, bigfishdesign13 approved these changes
The changes look good.  I will be creating new tickets to address the shift related to the `Select` focus state and to deal with the UX/dev to add a visible label.

2021-10-07 21:44 UTC, merged