DSD-523: Updating margins in the TextInput component
NYPL/nypl-design-system pull request #721
Opened 2021-10-13 21:56 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-523](https://jira.nypl.org/browse/DSD-523)

## This PR does the following:
- Removes the bottom margins from the `TextInput` and its `HelperErrorText` component.

## How has this been tested?

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2021-10-13 22:03 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr721-u03b21jztmtb93o2fi805dj4dilml4jn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/616756194dc8a8153f8f3803

2021-10-14 20:54 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr721-u03b21jztmtb93o2fi805dj4dilml4jn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/616756194dc8a8153f8f3803

2021-10-15 14:33 UTC, bigfishdesign13 requested changes
The bottom margin on the `HelperErrorText` element needs some adjustments.  I didn't think about it when I put this ticket together, but this same issue also appears on any input component that uses `HelperErrorText`.  When these components are dropped into the `Form` layout component, the bottom margin on `HelperErrorText` throws things out of whack.

2021-10-15 14:33 UTC, bigfishdesign13 commented on src/theme/components/textInput.ts
> -      ...helperTextMargin,
You can actually keep this.  The element that needs to be adjusted is the actual `HelperErrorText` component.  By default, the `HelperErrorText` component has a bottom margin.  That bottom margin should be removed from that element altogether or the styles should be rewritten to only add a bottom margin when the `HelperErrorText` element is not the `last-child`.

2021-10-15 19:15 UTC, EdwinGuzman commented
How about we close this and I make the appropriate update in DSD-509 #725 ?

2021-10-15 20:00 UTC, bigfishdesign13 commented
> How about we close this and I make the appropriate update in DSD-509 #725 ?

There are two margin values that need to be removed.  Yes, one is on the `HelperErrorText` component, but one is part of the `TextInput` styles.

2021-10-15 20:37 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr721-u03b21jztmtb93o2fi805dj4dilml4jn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/616756194dc8a8153f8f3803

2021-10-15 21:06 UTC, bigfishdesign13 approved these changes
Simple.  Clean.  Looks good.

2021-10-18 13:30 UTC, merged