DSD-531: Chakra List
NYPL/nypl-design-system pull request #726
Opened 2021-10-15 18:40 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-531](https://jira.nypl.org/browse/DSD-531)

## This PR does the following:
- Updates the `List` component to use Chakra.
- Updates other references.
- Also fixes a rendering issue with the "Colors" documentation Storybook page (`Breadcrumbs` wasn't updated).
- This is a precursor to updating the `Pagination` component, so updated this first.

## How has this been tested?

Storybook.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2021-10-19 22:08 UTC, bigfishdesign13 requested changes
Looks quite good.  Just need to tweak some of the CSS.

2021-10-19 22:08 UTC, bigfishdesign13 commented on src/theme/components/list.ts
> +        _before: {
To bring this into better alignment with the Figma designs, please make the following changes to the `_before` object.
- add `fontSize: "2"`
- add `lineHeight: "normal"`
- change to `marginLeft: "-.75rem"`
- change to `width: "1rem"`

2021-10-19 22:08 UTC, bigfishdesign13 commented on src/theme/components/list.ts
> +        gridTemplateColumns: { base: "100%", md: "max(225px) 1fr" },
The width of the first column was executed incorrectly in the original build of this component.  To fix that error, bump the width value from `225px` up to `250px`.

2021-10-19 22:08 UTC, bigfishdesign13 commented on src/theme/components/list.ts
> +  baseStyle: ({ noStyling }) => ({
To bring this into better alignment with the Figma designs, please add the following code to the `baseStyle` object.
```
li: {
  _notFirst: {
    marginTop: "xxs",
  }
},
```

2021-10-19 22:08 UTC, bigfishdesign13 commented on src/components/StyleGuide/Colors.stories.mdx
> +    <List type={ListTypes.Unordered} className="card-grid__cards" noStyling>
In the updates for the CSS prefix, I removed all of these `List` components and replaced with `SImpleGrid`.  This should make for a fun merge.

2021-10-20 14:30 UTC, EdwinGuzman commented on src/components/StyleGuide/Colors.stories.mdx
> +    <List type={ListTypes.Unordered} className="card-grid__cards" noStyling>
I'll make this update after the CSS Prefix pr is merged to make the merge easier.

2021-10-20 14:32 UTC, EdwinGuzman commented
Updated all expect the `Colors.stories.mdx` file (will wait until the CSS prefix PR is merged).

2021-10-21 16:25 UTC, bigfishdesign13 requested changes
Sorry, some of the values I gave you yesterday were not correct.  Please see my comments.

2021-10-21 16:25 UTC, bigfishdesign13 commented on src/theme/components/list.ts
> +          lineHeight: "normal",
Sorry for additional changes.  This needs to be changed to `lineHeight: "0.9"`.

2021-10-21 16:25 UTC, bigfishdesign13 commented on src/theme/components/list.ts
> +          marginLeft: "-.75rem",
Again, sorry for additional changes.  This needs to be changed to `marginLeft: "-1rem"`.

2021-10-21 20:52 UTC, bigfishdesign13 approved these changes
This may be cheating because I made the last update, but I am approving this PR.

2021-10-22 22:19 UTC, merged