DSD-537: Chakra HorizontalRule
NYPL/nypl-design-system pull request #732
Opened 2021-10-20 18:32 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-537](https://jira.nypl.org/browse/DSD-537)

## This PR does the following:
- Updates the `HorizontalRule` to use Chakra.

## How has this been tested?

Storybook.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2021-10-20 18:38 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr732-vshe6qkt1acaud7xqlzidrr2cm3sekrs.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/617060a18c559d056c1a7abe

2021-10-20 20:47 UTC, bigfishdesign13 requested changes
Some questions and one change requested.

2021-10-20 20:47 UTC, bigfishdesign13 commented on src/components/HorizontalRule/HorizontalRule.stories.mdx
> +    args={{
I'd like the initial view of the component to be the default version, without any props passed in.  Users can then configure what they need.

2021-10-20 20:47 UTC, bigfishdesign13 commented on src/components/HorizontalRule/HorizontalRule.test.tsx
> -  it("Renders with correct width and height values", () => {
Why was this test removed?  Too granular?

2021-10-20 20:49 UTC, EdwinGuzman commented on src/components/HorizontalRule/HorizontalRule.test.tsx
> -  it("Renders with correct width and height values", () => {
The width and height are now inputs into the compiled styles rather than directly added to the `style` attribute in the element. So this way of testing for those values isn't possible.

2021-10-21 01:35 UTC, bigfishdesign13 commented on src/components/HorizontalRule/HorizontalRule.test.tsx
> -  it("Renders with correct width and height values", () => {
Ah, but of course. :)

2021-10-21 13:34 UTC, bigfishdesign13 requested changes
I'm so sorry.  I missed something when I reviewed yesterday.  There is one more change needed.

2021-10-21 13:34 UTC, bigfishdesign13 commented on src/theme/components/horizontalRule.ts
> +    marginLeft: align === "left" ? 0 : null,
Sorry, I missed this yesterday.  The `null` values for `marginLeft` and `marginRight` should be changed to `auto`.  Without this change, the `hr` does not center itself when the `width` is less than 100%.

2021-10-21 18:15 UTC, bigfishdesign13 approved these changes
Looks good.

2021-10-22 22:14 UTC, merged