DSD-611: Button NoBrand
NYPL/nypl-design-system pull request #770
Opened 2021-11-18 15:13 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-611](https://jira.nypl.org/browse/DSD-611)

## This PR does the following:
- Add the `NoBrand` variant for the `Button` component.

## How has this been tested?

Storybook

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2021-11-18 15:18 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr770-p5pvfy8vwqah7b49zztpo5umuggtv0iw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61966d96de4970639ae404a2

2021-11-19 17:44 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr770-p5pvfy8vwqah7b49zztpo5umuggtv0iw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61966d96de4970639ae404a2

2021-11-22 18:29 UTC, bigfishdesign13 requested changes
Just one small change for the hover state.

2021-11-22 18:29 UTC, bigfishdesign13 commented on src/theme/components/button.ts
> +    opacity: "0.8",
For the `hover` state, remove `opacity` and change `bg` to `ui.gray.xdark`.

2021-11-22 22:38 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr770-p5pvfy8vwqah7b49zztpo5umuggtv0iw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61966d96de4970639ae404a2

2021-11-22 22:53 UTC, bigfishdesign13 approved these changes
All good.

2021-11-23 16:28 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr770-p5pvfy8vwqah7b49zztpo5umuggtv0iw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61966d96de4970639ae404a2

2021-11-23 16:44 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr770-p5pvfy8vwqah7b49zztpo5umuggtv0iw.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61966d96de4970639ae404a2

2021-11-23 17:14 UTC, merged