DSD-646: Label bottom margin
NYPL/nypl-design-system pull request #807
Opened 2021-12-13 21:35 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-646](https://jira.nypl.org/browse/DSD-646)

## This PR does the following:

- Updates the bottom margin for labels and legends in form components from "s" to "xs". The components affected include: `CheckboxGroup`, `DatePicker`, `Fieldset`, `RadioGroup`, `Select`, `Slider`, and `TextInput`.

## How has this been tested?

In Storybook. `Select` and `TextInput` are missing snapshot tests but I'll create a separate ticket for that.

## Accessibility concerns or updates

- None, it's just appearance.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2021-12-13 21:40 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr807-2vngdticla7tiiwhrjjbenpvcljjljys.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b7bca05f46ed13d8cdc178

2021-12-14 18:45 UTC, bigfishdesign13 requested changes
I didn't know this was a one-liner.  Awesome.  Just asking for one minor alteration to the CHANGELOG entry.

2021-12-14 18:45 UTC, bigfishdesign13 commented on CHANGELOG.md
> +- Updates the bottom margin on labels and legends for form components.
Can this be more specific?  `Reduces the bottom margin from 16px to 8px...`

2021-12-16 14:18 UTC, EdwinGuzman commented
Yeah, I'm glad these are one-liners because it makes the styles more consistent throughout.

2021-12-16 14:22 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr807-2vngdticla7tiiwhrjjbenpvcljjljys.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b7bca05f46ed13d8cdc178

2021-12-16 15:13 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr807-2vngdticla7tiiwhrjjbenpvcljjljys.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b7bca05f46ed13d8cdc178

2021-12-20 21:35 UTC, bigfishdesign13 approved these changes
Looks good.  Thanks for making the change.

2021-12-22 17:16 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr807-2vngdticla7tiiwhrjjbenpvcljjljys.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61b7bca05f46ed13d8cdc178

2021-12-22 17:16 UTC, merged