DSD-652: Card custom image aspect ratio fix
NYPL/nypl-design-system pull request #818
Opened 2021-12-21 16:25 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-652](https://jira.nypl.org/browse/DSD-652)

## This PR does the following:

- Fixes the bottom padding on custom image components/elements passed to the `Card` component by passing the appropriate aspect ratio value.
- Also fixes the logic in the `Image` component so custom components/elements don't get wrapped in cropping and aspect ratio divs.

## How has this been tested?

Locally in Storybook and through the NYPL test app with the Nextjs `Image` component.

## Accessibility concerns or updates

- None.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2021-12-21 16:29 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr818-fgntzdfg9hb5y5bqb39buazzpkhfzs6m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c1fff85f46ed13d84f18f7

2021-12-21 23:48 UTC, bigfishdesign13 requested changes
Looks good.  Just need to add the console warning.

2021-12-21 23:48 UTC, bigfishdesign13 commented on src/components/Card/Card.tsx
> +  const finalImageAspectRatio = imageComponent
Can you add a console warning if both a `imageComponent` and `imageAspectRatio` are set?  The message should say that `imageAspectRatio` will be ignored in favor of the aspect ratio on `imageComponent`.

2021-12-22 17:57 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr818-fgntzdfg9hb5y5bqb39buazzpkhfzs6m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c1fff85f46ed13d84f18f7

2021-12-22 19:15 UTC, bigfishdesign13 approved these changes
Very nice.

2022-01-03 15:54 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr818-fgntzdfg9hb5y5bqb39buazzpkhfzs6m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c1fff85f46ed13d84f18f7

2022-01-03 17:07 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr818-fgntzdfg9hb5y5bqb39buazzpkhfzs6m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c1fff85f46ed13d84f18f7

2022-01-03 18:06 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr818-fgntzdfg9hb5y5bqb39buazzpkhfzs6m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c1fff85f46ed13d84f18f7

2022-01-03 21:41 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr818-fgntzdfg9hb5y5bqb39buazzpkhfzs6m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c1fff85f46ed13d84f18f7

2022-01-04 14:50 UTC, EdwinGuzman commented
@wluisi can you take a look when you get a chance?

2022-01-04 14:54 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr818-fgntzdfg9hb5y5bqb39buazzpkhfzs6m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c1fff85f46ed13d84f18f7

2022-01-04 21:36 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr818-fgntzdfg9hb5y5bqb39buazzpkhfzs6m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c1fff85f46ed13d84f18f7

2022-01-06 21:26 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr818-fgntzdfg9hb5y5bqb39buazzpkhfzs6m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c1fff85f46ed13d84f18f7

2022-01-07 21:51 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr818-fgntzdfg9hb5y5bqb39buazzpkhfzs6m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c1fff85f46ed13d84f18f7

2022-01-18 15:46 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr818-fgntzdfg9hb5y5bqb39buazzpkhfzs6m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c1fff85f46ed13d84f18f7

2022-01-18 16:57 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr818-fgntzdfg9hb5y5bqb39buazzpkhfzs6m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c1fff85f46ed13d84f18f7

2022-01-20 20:48 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr818-fgntzdfg9hb5y5bqb39buazzpkhfzs6m.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c1fff85f46ed13d84f18f7

2022-01-20 21:48 UTC, nypl-wluisi approved these changes
Tested this branch out in the Scout app and it works. I can remove the wrapper box div around the Card images now, and no more extra bottom padding!

2022-01-21 14:01 UTC, merged