DSD-666: image bottom margin
NYPL/nypl-design-system pull request #819
Opened 2021-12-21 16:37 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-666](https://jira.nypl.org/browse/DSD-666)

## This PR does the following:

- Adds bottom margin to the `Image` component when used in the `Card` component and the `imageAspectRatio` prop is set to `ImageRatios.Original`.

## How has this been tested?

Locally in Storyboook.

## Accessibility concerns or updates

- None.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2021-12-21 16:39 UTC, EdwinGuzman commented
Please review #819  first as I branched off that branch by accident so the commit/changes look off.

2021-12-21 16:42 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr819-s7jqrcyfuxghw2mpaw2f6fczgmqayfuj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c202bfdc579fc65d475485

2021-12-21 23:59 UTC, bigfishdesign13 requested changes
The update is working, but its scope needs to be narrowed a bit.  Please see my comment.

2021-12-21 23:59 UTC, bigfishdesign13 commented on src/theme/components/card.ts
> +          marginBottom: "xs",
Sorry, I did not correctly specify that this bottom margin only needs to be applied for `ImageRatios.Original` in the `column` layout.  The image in the `row` layout does not need a bottom margin.

2021-12-22 18:45 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr819-s7jqrcyfuxghw2mpaw2f6fczgmqayfuj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c202bfdc579fc65d475485

2021-12-22 19:20 UTC, bigfishdesign13 approved these changes
Looks good now.

2022-01-03 16:03 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr819-s7jqrcyfuxghw2mpaw2f6fczgmqayfuj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c202bfdc579fc65d475485

2022-01-03 17:11 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr819-s7jqrcyfuxghw2mpaw2f6fczgmqayfuj.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61c202bfdc579fc65d475485

2022-01-03 18:00 UTC, merged