WIP: POC of using Modal in two separate ways
NYPL/nypl-design-system pull request #839
Opened 2022-01-10 16:10 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-703](https://jira.nypl.org/browse/DSD-703)

## This PR does the following:

- Is an exploration for the `Modal` component and how devs might/should use it.

## How has this been tested?

This is just a POC so we'll close this eventually once we agree on how to move forward.

## Accessibility concerns or updates

-

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2022-01-10 16:17 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr839-lll4qwnkt7xviitqcfqpnq7735kciohu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61dc5a737499db652205bde9

2022-01-11 17:02 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr839-lll4qwnkt7xviitqcfqpnq7735kciohu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61dc5a737499db652205bde9

2022-01-11 20:14 UTC, bigfishdesign13 approved these changes
I added some comments about the prop names, but those issues can be addressed in the final.

2022-01-11 20:14 UTC, bigfishdesign13 commented on src/components/Modal/Modal.tsx
> +  bodyContent = testBodyContent,
Update to `modalBodyContent`.

2022-01-11 20:14 UTC, bigfishdesign13 commented on src/components/Modal/Modal.stories.mdx
> +  headingText="Heading text"
Update to reflect the new naming convention: `modalHeadingText` and `modalBodyContent`.

2022-01-11 20:14 UTC, bigfishdesign13 commented on src/components/Modal/Modal.tsx
> +  headingText,
Update to `modalHeadingText`.

2022-01-18 16:52 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr839-lll4qwnkt7xviitqcfqpnq7735kciohu.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61dc5a737499db652205bde9

2022-01-18 18:24 UTC, EdwinGuzman commented
Closing but using code for final DSD-412 ticket.

2022-04-21 17:34 UTC, EdwinGuzman commented
@wluisi @bigfishdesign13  let's talk about this soon and see if it'll work in the upcoming work Bill is doing.

2022-04-21 17:37 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr839-gt9wbfjexcxmm0ivt9qtpeb37soj5xfr.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/626190762e91387b17150894

2022-04-21 18:12 UTC, nypl-wluisi approved these changes
This looks good to me. I like how you wrapped the Chakra hook `useDisclosure` with `useModal` and handle some the heavy lifting there. It makes the dev experience of using DS modal simpler. There is some potential overlap here w/ what I'm trying to do on `MultiSelect` dialog version, but we'd have to discuss that, it might make sense to deal with that after the initial version of `MultiSelect`.

In regards to this specific work, there is also a prop called `defaultIsOpen` in `useDisclosure`, which might be worth adding here? Not sure the value tho, it allowing consuming apps to have a modal "open by default" but just an idea.

2022-04-21 19:23 UTC, EdwinGuzman commented
From meeting:

- Expose the `onClose` function in the `useModal` hook
- allow jsx for the body content
- allow "full" size style only for mobile

2022-04-22 21:15 UTC, EdwinGuzman commented
This is ready to be tested now. I added an example and you can create your custom open and close buttons. I'll fix the tugboat issue later.

<img width="854" alt="Screen Shot 2022-04-22 at 5 15 09 PM" src="https://user-images.githubusercontent.com/1280564/164794480-b3669b5d-b754-4f10-b7f1-8056033cfda8.png">

2022-04-25 13:57 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr839-igsfimtu3yrifbrtmguioescildxk2ye.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/626304fb2e91387b1726e343

2022-04-25 17:51 UTC, bigfishdesign13 requested changes
A few small changes to get the component more inline with where we are headed with this component.

2022-04-25 17:51 UTC, bigfishdesign13 commented on src/components/Modal/Modal.tsx
> +      if (windowDimensions.width <= 320) {
Change the trigger width to 600px to align with our breakpoints.

2022-04-25 17:51 UTC, bigfishdesign13 commented on src/components/Modal/Modal.tsx
> +      <ChakraModal
This functionality needs to be implemented:
https://v0.chakra-ui.com/modal#modal-overflow-behavior

To do this, add the following prop to the modal component:
```
scrollBehavior=“inside"
```

2022-04-25 19:44 UTC, EdwinGuzman commented
Updated.

2022-04-25 19:49 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr839-igsfimtu3yrifbrtmguioescildxk2ye.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/626304fb2e91387b1726e343

2022-04-25 20:01 UTC, bigfishdesign13 approved these changes
This looks very good now.  We’ll need to adjust some more styles eventually, but the scrolling functionality is now in line with the final component.

2022-04-26 19:50 UTC, oliviawongnyc approved these changes
Looks good! Excited to try out the hook.

2022-04-26 21:21 UTC, merged