DSd-708: Fixing nested footer elements in TemplateAppContainer
NYPL/nypl-design-system pull request #841
Opened 2022-01-11 21:11 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-708](https://jira.nypl.org/browse/DSD-708)

## This PR does the following:

- This fixes an issue when a custom component meant to render a `<footer>` element is passed to the `TemplateAppContainer` or `TemplateFooter` components. For the new `renderFooterElement` prop, when it is set to false, a default `footer` element won't be rendered. This fixes the nested HTML `<footer>` elements.

## How has this been tested?

Storybook and tests.

## Accessibility concerns or updates

- Not anymore. It's not a syntax issue but a semantic issue to have nested footer elements.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2022-01-11 21:22 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr841-88nea9geux34jyun5gy92lyaezq9qnlo.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61ddf2885f46ed13d82415ec

2022-01-18 16:51 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr841-88nea9geux34jyun5gy92lyaezq9qnlo.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61ddf2885f46ed13d82415ec

2022-01-19 12:31 UTC, bigfishdesign13 requested changes
I asked to one addition.  Let me know if you think it is unnecessary.

2022-01-19 12:31 UTC, bigfishdesign13 commented on src/components/Template/Template.tsx
> +    <Box as="footer">{children}</Box>
Can you add a warning message if a `footer` element is passed in as a child in this scenario?

2022-01-19 15:51 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr841-88nea9geux34jyun5gy92lyaezq9qnlo.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61ddf2885f46ed13d82415ec

2022-01-20 13:45 UTC, bigfishdesign13 approved these changes
Looks good.

2022-01-20 19:54 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr841-88nea9geux34jyun5gy92lyaezq9qnlo.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/61ddf2885f46ed13d82415ec

2022-01-20 19:58 UTC, merged