DSD-797: Adding 'aboveHeader' prop and 'TemplateAboveHeader' component
NYPL/nypl-design-system pull request #875
Opened 2022-02-17 21:21 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-797](https://jira.nypl.org/browse/DSD-797)

## This PR does the following:

- Adds an `aboveHeader` prop to `TemplateAppContainer` to render content immediately before the header region.
- Adds the `TemplateAboveHeader` individual component which is used internally in the `TemplateAppContainer`. This gets rendered from edge-to-edge.

## How has this been tested?

Locally in Storybook.

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2022-02-17 21:27 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr875-hwtkvy8pmxtikp2gcdntrsuc9swfic6b.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/620ebc639efcc90b3e8a0d66

2022-02-18 17:11 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr875-hwtkvy8pmxtikp2gcdntrsuc9swfic6b.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/620ebc639efcc90b3e8a0d66

2022-02-22 13:31 UTC, bigfishdesign13 requested changes
Looks good and works well.  Just one request for additional documentation.

2022-02-22 13:31 UTC, bigfishdesign13 commented on src/components/Template/Template.tsx
> + * This optional component renders its children from edge-to-edge and should
I didn’t see anything in the updated documentation that talked about the a11y reasoning for adding this template region. Can you add something?

2022-02-22 13:57 UTC, bigfishdesign13 commented
@EdwinGuzman Can you also update the Figma link?  See the correct link below.

https://www.figma.com/file/qShodlfNCJHb8n03IFyApM/Main?node-id=36835%3A26688

2022-02-22 14:54 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr875-hwtkvy8pmxtikp2gcdntrsuc9swfic6b.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/620ebc639efcc90b3e8a0d66

2022-02-22 16:04 UTC, bigfishdesign13 approved these changes
Looks good.

2022-02-22 16:31 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr875-hwtkvy8pmxtikp2gcdntrsuc9swfic6b.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/620ebc639efcc90b3e8a0d66

2022-02-22 16:33 UTC, merged