DSD-825: Updating margins for List ul and ol
NYPL/nypl-design-system pull request #889
Opened 2022-03-07 15:15 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-825](https://jira.nypl.org/browse/DSD-825)

## This PR does the following:

- Adds top and bottom margin to the `Unordered` and `Ordered` `List` types.
- Removes the `.nypl p` bottom margin rule and moves it to the Chakra global file.

## How has this been tested?

Storybook.

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2022-03-07 15:20 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr889-c26bi2eel0eruwqk0bz71eqgewrxstuy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622621a801c6d20b85302bbd

2022-03-07 16:08 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr889-c26bi2eel0eruwqk0bz71eqgewrxstuy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622621a801c6d20b85302bbd

2022-03-07 17:54 UTC, bigfishdesign13 requested changes
One adjustment needed.  Sorry, some of my details in the Jira ticket were contradictory.

2022-03-07 17:54 UTC, bigfishdesign13 commented on src/theme/components/list.ts
> +  marginTop: "s",
`marginTop` can be removed.  (Or maybe it needs to be explicitly set to `0`?)  The spacing for `ul` and `ol` should be identical to the `p` element.

2022-03-07 17:54 UTC, bigfishdesign13 commented on src/styles/base/_03-base.scss
> -  p {
:)

2022-03-08 15:34 UTC, EdwinGuzman commented
Updated. Made them also global to any ul, ol, and p elements just in case they are used without `Text` or `List`.

2022-03-08 15:38 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr889-c26bi2eel0eruwqk0bz71eqgewrxstuy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622621a801c6d20b85302bbd

2022-03-08 17:54 UTC, bigfishdesign13 approved these changes
Great.  I like that you made the `ul` and `ol` styles global.  I was initially concerned that a consuming app might be using `ul` to render something other than text and these styles would not really apply.  However, `ul` is being used like that, then there will most likely be other styles within the consuming app that will handle the margins and override what we have here.

2022-03-10 16:34 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr889-c26bi2eel0eruwqk0bz71eqgewrxstuy.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622621a801c6d20b85302bbd

2022-03-10 17:05 UTC, merged