DSD-826: font size and text wrap updates to the Radio, Checkbox, and Toggle
NYPL/nypl-design-system pull request #897
Opened 2022-03-10 22:52 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-826](https://jira.nypl.org/browse/DSD-826)

## This PR does the following:

- Updates the Radio's and Checkbox's label font size to "label.default".
- Fixes alignment for long labels in the `Checkbox` and `Radio` components.
- Fixes the line height for long labels in the `Toggle` component.

This took longer than expected because the styles did not update as I expected them to. The theme object didn't work and neither did using the `sx` prop over the `__css` prop. The rules had to be added at the top level under the "sizes" property but I don't know why. And some alignment and the line height had to be added directly as Chakra style props to the Chakra components -- and again, I don't know why.

## How has this been tested?

Storybook.

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2022-03-10 22:56 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr897-ukgoy3x5tafozhzfj7wxpyokeoag0cqn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622a8121af445bb315e2bb32

2022-03-14 15:46 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr897-ukgoy3x5tafozhzfj7wxpyokeoag0cqn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622a8121af445bb315e2bb32

2022-03-14 16:13 UTC, bigfishdesign13 requested changes
`Checkbox` and `Radio` work well, but `Toggle` needs a bit more work.  The text in `Toggle` is wrapping nicely now, but the vertical alignment also needs to be addressed.  You should be able to use the same `alignItems` update that was applied to the other two, but the `Large` variant will also need padding added to the top of the label text to get it to align better with the increased height of the `Large` variant.  I think `marginTop: 5px` would do it.  It kills me that it does not align with our spacing values, but oh well.

2022-03-14 16:13 UTC, bigfishdesign13 commented on src/components/Toggle/Toggle.tsx
> +            lineHeight="1.5"
Why does `Toggle` need this, but `Checkbox` and `Radio` do not?

2022-03-15 18:15 UTC, EdwinGuzman commented on src/components/Toggle/Toggle.tsx
> +            lineHeight="1.5"
No idea but this is what fixed the text overlap.

2022-03-15 18:46 UTC, EdwinGuzman commented
When the text is very long, I don't see much of a difference with the marginTop for the large `Toggle`. If I add that rule and have only one word for the label, it does not align with the `Toggle`'s control anymore. The following is with `marginTop: "5px"` but short label text:

<img width="386" alt="Screen Shot 2022-03-15 at 2 36 05 PM" src="https://user-images.githubusercontent.com/1280564/158449352-fb19b110-9637-44c8-8fc7-769c0f25aae9.png">

I don't think we can add a logic check for when there is very long text and adding a marginTop.

2022-03-15 18:50 UTC, EdwinGuzman commented
Added the `alignItems` but I don't see much of a change.

2022-03-15 18:52 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr897-ukgoy3x5tafozhzfj7wxpyokeoag0cqn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622a8121af445bb315e2bb32

2022-03-15 19:01 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr897-ukgoy3x5tafozhzfj7wxpyokeoag0cqn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622a8121af445bb315e2bb32

2022-03-15 19:05 UTC, bigfishdesign13 commented on src/components/Toggle/Toggle.tsx
> +            lineHeight="1.5"
OK, that’s sufficient for me. :)

2022-03-15 20:21 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr897-ukgoy3x5tafozhzfj7wxpyokeoag0cqn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622a8121af445bb315e2bb32

2022-03-15 20:48 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr897-ukgoy3x5tafozhzfj7wxpyokeoag0cqn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622a8121af445bb315e2bb32

2022-03-16 14:08 UTC, EdwinGuzman commented
@bigfishdesign13 the last update looks good.

2022-03-17 13:38 UTC, bigfishdesign13 approved these changes
Teamwork!

2022-03-17 18:37 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr897-ukgoy3x5tafozhzfj7wxpyokeoag0cqn.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/622a8121af445bb315e2bb32

2022-03-17 18:38 UTC, merged