DSD-854: Updating all console warnings with NYPL branding
NYPL/nypl-design-system pull request #917
Opened 2022-03-25 14:46 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-854](https://jira.nypl.org/browse/DSD-854)

## This PR does the following:

- Updates all console warnings with NYPL branding.
- Adds missing tests for some console warning messages.

## How has this been tested?

Unit tests

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2022-03-25 14:51 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr917-idbgjglu5gydpdezojbhbabq0fuur1n3.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/623dd5c1628e351b6b786e54

2022-03-25 16:41 UTC, bigfishdesign13 requested changes
The writing style changes throughout the warning messages.  I tried to address those where the differences were significant, but overall there are still a number that I did not address.  I think we should go the route of full sentences, or somethign very close.  What do you think?

2022-03-25 16:41 UTC, bigfishdesign13 commented on src/components/DatePicker/DatePicker.tsx
> +        "NYPL Reservoir DatePicker: React `ref` props were passed and an `onChange` prop as well. Use whichever is best for your app but not both."
Could be clearer.
```
React `ref` and `onChange` props were both passed. Use…
```

Or should should `ref` be referred to in a singular sense?  `prop` vs `props`?

2022-03-25 16:41 UTC, bigfishdesign13 commented on src/components/Hero/Hero.tsx
> +        `NYPL Reservoir Hero: it is recommended to use the "backgroundImageSrc" prop for PRIMARY hero.`
`PRIMARY` should not be capitalized, but I am not exactly sure what it should be replaced with.  `HeroTypes.Primary`?  And this change is applicable to all references to the `Hero` types.

2022-03-25 16:41 UTC, bigfishdesign13 commented on src/components/Hero/Hero.tsx
> +      `NYPL Reservoir Hero: Please provide "locationDetails" only to PRIMARY hero.`
Could be clearer.
```
NYPL Reservoir Hero: the "locationDetails” prop should only be used with HeroTypes.Primary.
```

2022-03-25 16:41 UTC, bigfishdesign13 commented on src/components/HorizontalRule/HorizontalRule.tsx
> +      "NYPL Reservoir HorizontalRule: For the `height` prop, use a whole number, a `px`" +
Could be clearer.
```
NYPL Reservoir HorizontalRule: An invalid value was passed for the `height` prop, so the default value of 2px will be used.  A valid value should be a whole number, a `px` value, a `em` value, or a `rem` value.
```

2022-03-25 16:41 UTC, bigfishdesign13 commented on src/components/Icons/Icon.tsx
> +      "NYPL Reservoir Icon: pass in either a `name` prop or an `svg` element child, not both."
```
NYPL Reservoir Icon: Pass in either a `name` prop or an `svg` element child. Do not pass both.
```

2022-03-25 16:41 UTC, bigfishdesign13 commented on src/components/List/List.tsx
> +      "NYPL Reservoir List: pass in either `<li>`, `<dt>`, or `<dd>` children or use the `listItems` data prop, but don't use both."
```
NYPL Reservoir List: Pass in either `<li>`, `<dt>`, or `<dd>` children or use the `listItems` data prop. Do not use both.
```

2022-03-25 16:41 UTC, bigfishdesign13 commented on src/components/Logo/Logo.tsx
> +      "NYPL Reservoir Logo: accepts either a `name` prop or an `svg` element child. It can not accept both."
```
NYPL Reservoir Logo: Pass either a `name` prop or an `svg` element child. Do not pass both.
```

2022-03-25 16:41 UTC, bigfishdesign13 commented on src/components/ProgressIndicator/ProgressIndicator.tsx
> +      "NYPL Reservoir ProgressIndicator: pass in a `value` between 0 and 100. Defaulting to 0."
```
NYPL Reservoir ProgressIndicator: An invalid value was passed for the `value` prop, so 0 will be used. A valid value should be a number between 0 and 100.
```

2022-03-25 16:41 UTC, bigfishdesign13 commented on src/components/StructuredContent/StructuredContent.tsx
> +      "NYPL Reservoir StructuredContent: `imageAlt` prop is required when using an image."
```
NYPL Reservoir StructuredContent: The `imageAlt` prop is required when using an image.
```

2022-03-25 16:41 UTC, bigfishdesign13 commented on src/components/VideoPlayer/VideoPlayer.tsx
> +      "NYPL Reservoir VideoPlayer: requires the `videoType` prop. Only the `videoId` prop was set."
```
NYPL Reservoir VideoPlayer: The `videoType` prop is also required. Only the `videoId` prop was set.
```

2022-03-25 16:41 UTC, bigfishdesign13 commented on src/components/VideoPlayer/VideoPlayer.tsx
> +      "NYPL Reservoir VideoPlayer: requires the `videoId` prop. Only the `videoType` prop was set."
```
NYPL Reservoir VideoPlayer: The `videoId` prop is also required. Only the `videoType` prop was set.
```

2022-03-25 21:18 UTC, EdwinGuzman commented
Sure, full sentences are fine. I was being a bit lazy and leaving the text as is. I'll update the rest.

2022-03-28 20:07 UTC, EdwinGuzman commented
Updated.

2022-03-28 20:12 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr917-idbgjglu5gydpdezojbhbabq0fuur1n3.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/623dd5c1628e351b6b786e54

2022-03-29 17:23 UTC, bigfishdesign13 requested changes
Looking very good.  Just a couple of small adjustments for clarity.

2022-03-29 17:23 UTC, bigfishdesign13 commented on src/components/Heading/Heading.tsx
> +      "NYPL Reservoir Heading: Only pass one child into Heading; got multiple children."
```
NYPL Reservoir Heading: Only pass one child into Heading. Multiple children have been passed.
```
Or even just this…
```
NYPL Reservoir Heading: Only pass one child into Heading.
```

2022-03-29 17:23 UTC, bigfishdesign13 commented on src/components/Pagination/Pagination.tsx
> +        "`onPageChange` are passed. Will default to using `getPageHref`."
```
… The component will default to using `getPageGref`.
```

2022-03-29 17:23 UTC, bigfishdesign13 commented on src/components/Select/Select.tsx
> +      "NYPL Reservoir Select: It is recommended that <select> fields have " +
After hearing about Bill’s woes with these warning messages, let’s remove both of these and instead include something about best practices on the `Select` story page.

2022-03-29 17:23 UTC, bigfishdesign13 commented on src/components/Tabs/Tabs.tsx
> +      "NYPL Reservoir Tabs: Only pass children or data in the `contentData` " +
```
NYPL Reservoir Tabs: Only pass children or data in the `contentData` prop. Do not pass both.
```

2022-03-31 17:25 UTC, bigfishdesign13 approved these changes
Nailed it!

2022-03-31 17:52 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr917-idbgjglu5gydpdezojbhbabq0fuur1n3.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/623dd5c1628e351b6b786e54

2022-03-31 18:01 UTC, merged