DSD-853: Allow CardActions to align to the right in the Card component
NYPL/nypl-design-system pull request #946
Opened 2022-04-12 16:32 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-853](https://jira.nypl.org/browse/DSD-853)

## This PR does the following:

- Adds the `isAlignedRightActions` prop to the `Card` component so that all of its `CarActions` children move to the right of the main content area.
- This is set only in the row layout.

## How has this been tested?

Storybook

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2022-04-12 16:36 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr946-jnwdpwqqf0ojmloisto12wrprf0hua4s.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6255a9b6db46ec1959cb1b78

2022-04-12 16:53 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr946-jnwdpwqqf0ojmloisto12wrprf0hua4s.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6255a9b6db46ec1959cb1b78

2022-04-12 17:27 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr946-jnwdpwqqf0ojmloisto12wrprf0hua4s.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6255a9b6db46ec1959cb1b78

2022-04-12 17:37 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr946-jnwdpwqqf0ojmloisto12wrprf0hua4s.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6255a9b6db46ec1959cb1b78

2022-04-15 16:22 UTC, bigfishdesign13 requested changes
Just need to clean up the styles for the new “action on right side” container.

2022-04-15 16:22 UTC, bigfishdesign13 commented on src/components/Card/Card.tsx
> +            __css={{ ...styles.body, marginLeft: "m" }}
The styles for this container need to be cleaned up.

Mobile View
- `width` should be `100%`
- `marginLeft` should be  `0`
- `marginTop` should be  `xs` (8px)

Desktop View
- `width` should be `180px`
- `marginLeft` should be `m`
- `marginTop` should be  `0`

2022-04-15 20:19 UTC, EdwinGuzman commented
Updated. FYI on how it looks with multiple buttons or links but I think it would be the responsibility of the content that is added rather than the `CardActions` component:
<img width="380" alt="Screen Shot 2022-04-15 at 4 03 30 PM" src="https://user-images.githubusercontent.com/1280564/163628363-028ecefc-1357-479c-bd26-5007ad004fdf.png">
<img width="1136" alt="Screen Shot 2022-04-15 at 4 03 17 PM" src="https://user-images.githubusercontent.com/1280564/163628364-cfa14fb2-3ef2-43ac-b245-70190ed93d4c.png">

2022-04-15 20:22 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr946-jnwdpwqqf0ojmloisto12wrprf0hua4s.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6255a9b6db46ec1959cb1b78

2022-04-19 13:35 UTC, bigfishdesign13 approved these changes
Looks good.  And yes, I agree.  The consuming app should be responsible for formatting their content to fit properly in a small space.  Of course, I think providing proper layout components to do that is our responsibility.  And we are getting there.

2022-04-19 14:41 UTC, merged