DSD-920: Updating styles for the datepicker's calendar popup
NYPL/nypl-design-system pull request #959
Opened 2022-04-15 19:34 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-920](https://jira.nypl.org/browse/DSD-920)

## This PR does the following:

- Updates the styles for `React Datepickers`'s calendar popup used in the `DatePicker` component.

## How has this been tested?

Storybook.

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2022-04-15 19:37 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr959-wk6u9rz2qzvsmmglcfa9t6q47o5l6i7w.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6259c8adbda4981539fd8288

2022-04-15 20:04 UTC, bigfishdesign13 commented
@EdwinGuzman Take a look at this on Mac Safari.  The prev/next arrows are not visible.  But this was not due to anything you added.  Apparently, it has always been like this.  It is from the positioning attributes.  If you fiddle with the inspect tools in the browser, you can eventually get them to show.  But other than that, I don’t know exactly which styles are causing this.

![image](https://user-images.githubusercontent.com/5241828/163626855-882d6ad4-f33e-4ac2-b8e2-696858a7db2c.png)

2022-04-18 19:44 UTC, EdwinGuzman commented
It looks like this is an existing bug in prod: https://nypl.github.io/nypl-design-system/storybook-static/?path=/story/components-form-elements-datepicker--date-picker-with-controls

2022-04-18 19:44 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr959-wk6u9rz2qzvsmmglcfa9t6q47o5l6i7w.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6259c8adbda4981539fd8288

2022-04-18 19:58 UTC, EdwinGuzman commented
Updated and fixed.

2022-04-18 20:02 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr959-wk6u9rz2qzvsmmglcfa9t6q47o5l6i7w.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6259c8adbda4981539fd8288

2022-04-19 13:32 UTC, bigfishdesign13 requested changes
The arrows look good, but some of the hover styles need to be tweaked.

2022-04-19 13:32 UTC, bigfishdesign13 commented on src/components/DatePicker/_DatePicker.scss
> +      color: var(--nypl-colors-ui-black);
The basic hover styles are overwriting these styles.  While it’s not a best practice, I think the color and BG color attributes here need to be locked in using `!important`.

2022-04-19 13:32 UTC, bigfishdesign13 commented on src/components/DatePicker/_DatePicker.scss
> +      background-color: var(--nypl-colors-ui-focus);
Same thing here.  The basic hover styles are overwriting these styles.  The color and BG color attributes here need to be locked in using `!important`.

2022-04-19 14:57 UTC, EdwinGuzman commented
Updated.

2022-04-19 15:01 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr959-wk6u9rz2qzvsmmglcfa9t6q47o5l6i7w.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6259c8adbda4981539fd8288

2022-04-19 17:55 UTC, bigfishdesign13 requested changes
Ugh.  One more change and one question.  Also, the `minDate` and `maxDate` on the `DatePicker` should be updated to more recent dates.

2022-04-19 17:55 UTC, bigfishdesign13 commented on src/components/DatePicker/_DatePicker.scss
>        opacity: 0.3;
This is causing trouble and I think it should be removed.  Can you find a usecase where it makes sense?

2022-04-19 17:55 UTC, bigfishdesign13 commented on src/components/DatePicker/_DatePicker.scss
> +      background-color: var(--nypl-colors-ui-gray-light-cool);
Becuase I am looking at what’s happening with the code on line 75, I can now see that this should be set to `var(--nypl-colors-ui-gray-x-light-cool)`

2022-04-19 18:55 UTC, EdwinGuzman commented
Regarding the last round of feedback, it was mostly because of the dates within a range of selected dates.
<img width="674" alt="Screen Shot 2022-04-19 at 2 53 04 PM" src="https://user-images.githubusercontent.com/1280564/164075506-49a8e5d2-0428-4d15-ac7c-cd9c5198b09f.png">

In this example, the "from" date is 4/13, today's date is 4/19, and the "to" date is 4/22. When I go to select 4/4, all the dates from 4 to 12 look the same as the dates within the selected dates of 4/13 to 4/22. So the opacity was there for that. But from the screenshot above, the same gray x-light-cool looks fine. What do you think?

2022-04-19 18:57 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr959-wk6u9rz2qzvsmmglcfa9t6q47o5l6i7w.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6259c8adbda4981539fd8288

2022-04-19 19:17 UTC, bigfishdesign13 approved these changes
The coloring in the example you showed looks good.  Thank you for working through these issues.

2022-04-19 20:24 UTC, EdwinGuzman commented
No problem!

2022-04-19 20:28 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr959-wk6u9rz2qzvsmmglcfa9t6q47o5l6i7w.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6259c8adbda4981539fd8288

2022-04-19 20:29 UTC, merged