DSD-929: SkipNav component
NYPL/nypl-design-system pull request #963
Opened 2022-04-19 19:09 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-929](https://jira.nypl.org/browse/DSD-929)

## This PR does the following:

- This is set for v1.0 so it can be reviewed later, but I wanted to get it in place so @oliviawongnyc can use this in the `Header`.
- Adds the skip navigational links through the `SkipNav` component (maybe should be renamed `SkipNavigation`?).

## How has this been tested?

Storybook in its own document page and in the `TemplateAppContainer` storybook page.

## Accessibility concerns or updates

- This is the second part of creating the accessible skip nav links. The first part is in the `TemplateAppContainer` component and is done through the `main`'s element `id` value of `"mainContent"`. The first link in the `SkipNav` component points to this target through the `"#mainContent"` hash.

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2022-04-19 19:18 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr963-lnoyreepw1wwbyhqwg4vrf8nccli94ko.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/625f08e72e91387b17f63546

2022-04-25 14:16 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr963-uij9gqz9e22degoewxpjnbdkanlpkmjh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6266aba82e91387b174879c2

2022-04-26 13:30 UTC, bigfishdesign13 requested changes
Some questions and some changes.

2022-04-26 13:30 UTC, bigfishdesign13 commented on src/components/AccessibilityGuide/SkipNavigation.stories.mdx
> +The `SkipNav` component renders two links, the first being the main link pointing
I see that other areas of the `SkipNav` and a11y documentation describe the second link, but I think that should be done here as well.

2022-04-26 13:30 UTC, bigfishdesign13 commented on src/components/AccessibilityGuide/SkipNavigation.stories.mdx
>  ## General Information
Now that we have a `SkipNav` component, do we need this much inofrmation here?  I am concerned about duplicate information here and in other areas of our docs.

2022-04-26 13:30 UTC, bigfishdesign13 commented on src/components/SkipNav/SkipNav.stories.mdx
> +links should be added before all the content on a page. The Reservoir achieves
Typo…
```The Reservoir Design System achieves…```

2022-04-26 13:30 UTC, bigfishdesign13 commented on src/components/Template/Template.stories.mdx
> +If you are using a custom header component or you need to use the Reservoir's
Typo…
```…need to use the Reservoir Design System (DS) `SkipNav`…```

After this is added, the reference to Reservoir under `Template Children Overview` can be updated to just `DS`.

2022-04-26 13:30 UTC, bigfishdesign13 commented on src/theme/components/skipNav.ts
> +      _focus: {
Let’s get this a little closer to the styles as it is currently implemented.  Add the following:
```
padding: var(--nypl-space-inset-extranarrow) var(--nypl-space-inset-narrow),
border: 1px solid var(—nypl-colors-ui-gray-dark)
```

2022-04-26 13:30 UTC, bigfishdesign13 commented on src/utils/componentCategories.ts
> +      "SkipNav",
I think `SkipNavigation` would be more applicable.

2022-04-27 21:18 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr963-uij9gqz9e22degoewxpjnbdkanlpkmjh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6266aba82e91387b174879c2

2022-04-28 14:31 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr963-uij9gqz9e22degoewxpjnbdkanlpkmjh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6266aba82e91387b174879c2

2022-04-28 14:57 UTC, EdwinGuzman commented on src/components/AccessibilityGuide/SkipNavigation.stories.mdx
>  ## General Information
Yeah, it seems redundant and I dont see other app-wide a11y guidelines anytime soon. The component a11y section is specific to the component while this specific page is more for how to use it and how it works in an application. That was my original intention. Should I still combine the two pages or keep them separate but refine them?

2022-04-28 15:08 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr963-uij9gqz9e22degoewxpjnbdkanlpkmjh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6266aba82e91387b174879c2

2022-04-28 16:57 UTC, bigfishdesign13 commented on src/components/AccessibilityGuide/SkipNavigation.stories.mdx
>  ## General Information
OK.  After reading your respnse (re: component specific info vs. site-wide standards and patterns), I do think this page is applicable.  And yes, some refinement would be good.

Other potential topics for this section coudl be `image alt text`, `form input labelling` and `color contrast`.

2022-04-28 19:33 UTC, EdwinGuzman commented
Updated PR.

2022-04-28 19:41 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr963-uij9gqz9e22degoewxpjnbdkanlpkmjh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6266aba82e91387b174879c2

2022-05-05 18:18 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr963-uij9gqz9e22degoewxpjnbdkanlpkmjh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6266aba82e91387b174879c2

2022-05-06 13:15 UTC, bigfishdesign13 approved these changes
UI updates look good.

2022-05-06 16:42 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr963-uij9gqz9e22degoewxpjnbdkanlpkmjh.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/6266aba82e91387b174879c2

2022-05-06 18:03 UTC, merged