DSD-944: Fixing Card layout when isAlignedRightActions is true
NYPL/nypl-design-system pull request #980
Opened 2022-04-28 18:22 UTC by EdwinGuzman

Fixes JIRA ticket [DSD-944](https://jira.nypl.org/browse/DSD-944)

## This PR does the following:

- Updates CSS for the "body" and "actions" section elements in the `Card` component when `isAlignedRightActions` is set to `true`.

## How has this been tested?

Storybook. I tested this with different elements and the different responsive views. Let me know if the changes you suggested are enough -- I only added them to the mobile view since adding them all the time did not render the desktop layout correctly.

## Accessibility concerns or updates

- N/A

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2022-04-28 18:29 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr980-l0z23aejgrtbuwl8dxrjv9o3zit4mjr9.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/626adb7aef17c6f569235c70

2022-05-05 18:15 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr980-l0z23aejgrtbuwl8dxrjv9o3zit4mjr9.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/626adb7aef17c6f569235c70

2022-05-06 13:25 UTC, bigfishdesign13 commented
@EdwinGuzman Which configurations were showing problems when `flexBasis: “100%”` was applied all the time?  Without that attribute, there are sizing problems when the text content is short.  This is easiest to see when the CardActions are set to the right.  Pull up that story in Storybook and use the browser dev tools to set the content to only a few words.  When you do that, the card body region will contract to the size of the text and the card actions region will slide to the left based on the size of the card body region.

2022-05-06 14:51 UTC, EdwinGuzman commented
I see the problem. It helps when the actions section has a max-width rather than just width of 180px. Check the update.

2022-05-06 14:55 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr980-l0z23aejgrtbuwl8dxrjv9o3zit4mjr9.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/626adb7aef17c6f569235c70

2022-05-06 18:26 UTC, bigfishdesign13 commented
@EdwinGuzman Yes, this now works well for the `actions on right` variant, but there are also sixing issues on for the standard row layout.  To see what I mean, do the same thing with the text for the initial `Card` story.  The actions region will shrink to be the same size as the text.

2022-05-09 15:50 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr980-l0z23aejgrtbuwl8dxrjv9o3zit4mjr9.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/626adb7aef17c6f569235c70

2022-05-10 17:25 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr980-l0z23aejgrtbuwl8dxrjv9o3zit4mjr9.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/626adb7aef17c6f569235c70

2022-05-10 18:06 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr980-l0z23aejgrtbuwl8dxrjv9o3zit4mjr9.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/626adb7aef17c6f569235c70

2022-05-17 20:00 UTC, bigfishdesign13 requested changes
Some minor changes to what you have will fix the width problems in this and other configurations.

2022-05-17 20:00 UTC, bigfishdesign13 commented on src/theme/components/card.ts
> +        flexBasis: { sm: isAlignedRightActions ? "100%" : null },
Changing `isAlignedRightActions` to `isRow` seems to fix the width problems for all `row` configurations.

2022-05-17 20:00 UTC, bigfishdesign13 commented on src/theme/components/card.ts
> +        maxWidth: { base: "100%", md: "180px" },
Adding `width: "100%”` to this block makes the actions element go to full width in a responsive view.

2022-05-18 18:35 UTC, EdwinGuzman commented
Updated.

2022-05-19 13:02 UTC, bigfishdesign13 requested changes
Sorry, one more update.  So many configs for this component.

2022-05-19 13:02 UTC, bigfishdesign13 commented on src/theme/components/card.ts
>        body: {
Ugh.  I found one more configuration that still needs to be cleaned up.  Please add the following to the styles for `body`:
```
width: { base: "100%", md: "auto" },
```

2022-05-20 15:15 UTC, bigfishdesign13 approved these changes
Looks good.  I think that is it!

2022-05-20 15:39 UTC, merged