DSD-949 - Heading add noSpace prop
NYPL/nypl-design-system pull request #988
Opened 2022-05-05 17:29 UTC by knezmilos

Fixes JIRA ticket DSD-949

## This PR does the following:

- add a noSpace prop to the Heading component where if set, it sets margin-bottom to 0

## How has this been tested?

## Accessibility concerns or updates

-

### Checklist:

- [ ] I have updated the Storybook documentation accordingly.
- [ ] I have added relevant accessibility documentation for this pull request.
- [ ] All new and existing tests passed.

### Front End Review:

- [ ] View [the example in Storybook]()

2022-05-05 18:01 UTC, EdwinGuzman requested changes
Minor updates, and make sure to merge the `development` branch into this branch and fix the conflicts.

2022-05-05 18:01 UTC, EdwinGuzman commented on CHANGELOG.md
> +- Added `noSpace` prop to the `Heading` component.
This should go under a new heading `### Adds` above the `### Updates` heading. Also, "Added" should be updated to "Adds" to keep the same tense.

2022-05-05 18:01 UTC, EdwinGuzman commented on src/components/Heading/Heading.tsx
> +    const styles = useStyleConfig("Heading", { variant, noSpace });
This is not needed because it's not being used in the relevant `src/theme/components/heading.ts` file. This is okay to remove.

2022-05-05 18:18 UTC, EdwinGuzman commented on src/components/Heading/Heading.tsx
> +    const styles = useStyleConfig("Heading", { variant, noSpace });
Update: let's keep this here and instead remove line 95 `mb={noSpace ? "0" : null}`.

2022-05-05 18:22 UTC, EdwinGuzman commented
The usage of passing `noSpace` to the `useStyleConfig` function is the right approach. As it currently stands, passing this variable to that function does nothing because it's not set up in `heading.ts`.

You'll find that in `heading.ts`, the function is declared as
```
const Heading = {
  baseStyle: {
    // This is to help target custom anchor elements
    // passed as children to the Heading component.
    a: baseLinkStyles,
  },
```

This needs to be updated as
```
const Heading = {
  baseStyle: ({ noSpacing }) =>{
    // This is to help target custom anchor elements
    // passed as children to the Heading component.
    a: baseLinkStyles,
  },
```

and then you can add the `mb` conditional logic. This is so that we can keep the logic for styles in the them file rather than in the component file.

One minor nitpick is to use `marginBottom` instead of `mb` because not everyone might be use to the Chakra-style shorthand. I prefer the clarity over the brevity.

2022-05-06 03:52 UTC, knezmilos commented
What seemed to work was removing "marginBottom" from the "margins" object on the top in order for it to be recognized in baseStyle function

2022-05-06 13:50 UTC, EdwinGuzman commented on src/theme/components/heading.ts
> +    };
Nitpick: can you update this to
```
baseStyle: ({ noSpace }) => ({
  // This is to help target custom anchor elements
  // passed as children to the Heading component.
  a: baseLinkStyles,
  marginBottom: noSpace? "0" : "s",
})
```

2022-05-06 13:51 UTC, EdwinGuzman commented
This is good to go but the merge conflicts should be fixed.

2022-05-08 02:20 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr988-o1drzhobwiiuqaft8ukh0y6ekdlszrwi.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62749b502e91387b1710f523

2022-05-09 14:07 UTC, EdwinGuzman reviewed
This looks good. We won't release this until after the v1.0.0 release so this will be merged next week.

2022-05-09 15:59 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr988-o1drzhobwiiuqaft8ukh0y6ekdlszrwi.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62749b502e91387b1710f523

2022-05-09 21:39 UTC, EdwinGuzman reviewed
Can you also update the latest version for the `Heading` component to "1.0.1" in `Heading.stories.mdx`? That's when this will be released.

2022-05-10 01:45 UTC, EdwinGuzman commented
[Tugboat](https://tugboat.qa) has finished building the preview for this pull request!

Link:
- https://pr988-o1drzhobwiiuqaft8ukh0y6ekdlszrwi.tugboat.qa


Dashboard:
- https://dashboard.tugboat.qa/62749b502e91387b1710f523

2022-05-10 17:24 UTC, EdwinGuzman approved these changes
Approving but needs to wait until 1.0.0 is released before merging.

2022-05-16 18:21 UTC, merged